/**
 * The car catalogue: complete, authored 3D models.
 *
 * The old concept built a car out of attachable parts. That is gone. A car is now
 * ONE finished imported model whose geometry is authoritative:
 *
 *  - the chassis collider comes from the model's `body` bounding box,
 *  - suspension mounts come from its wheel nodes,
 *  - each wheel's radius comes from that wheel node's own bounds,
 *
 * all measured at load time in render/carmodel.ts. This catalogue holds geometry's
 * defaults: mass, gearbox, original engine, tank capacity, springs and steering.
 *
 * Every catalogue model is roadworthy. A wreck is a STATE a body is found in, not a
 * class of body: the same twenty models supply the player's car, the working
 * cars generated at roadside stops, and the sunken shells scattered beside them.
 *
 * Free-form anchor parts remain cosmetic. The separate four-cell bonnet service
 * layout owns the removable engine, optional turbine, radiator and fuel tank.
 */

import type { BodyClass, EngineSpec, GearboxSpec, SuspensionTuning } from '../parts/registry';
import { variant } from '../parts/registry';
import modelFits from './model-fits.json';

import { TRUNK_CELL_COUNT } from './trunk';
const MODEL_FITS = modelFits as unknown as Record<string, CarModelFit>;
function modelFit(id: string): CarModelFit {
  const fit = MODEL_FITS[id];
  if (!fit) throw new Error(`Model "${id}" is missing fit metadata`);
  return fit;
}


/**
 * The vendored packs, each credited beside its models, and the cars built here.
 *
 *  - SOVIET: Low Poly Soviet Car Pack. Fifteen FBX bodies in centimetres, each
 *    carrying its own wheels, colour taken from a shared 9x2 swatch atlas.
 *  - SAAS: private GTA SA mod conversions, normalized offline into texture-free
 *    GLBs with six runtime material roles and explicit wheel, hub and lamp nodes.
 *  - GTAV: GTA V add-on fragments (.yft inside an .rpf), normalized by
 *    `tools/import-yft-vehicle.py` into the same texture-free contract as SAAS.
 *    Its wheels are one authored assembly instanced at four corners, so these
 *    bodies have wheel nodes and no separate hub nodes.
 *  - CARFORGE: bodies generated by `tools/carforge` from a factory drawing, in the
 *    Soviet pack's own form: FBX in centimetres, nose down +Z, colour by UV from the
 *    pack's 9x2 atlas, glass in its (3, 1) cell, one node per lamp role.
 */
const SOVIET = '/models/soviet';
const SAAS = '/models/saas';
const GTAV = '/models/gtav';
const CARFORGE = '/models/carforge';

/* ---- suspension presets ----
 *
 * Written in the four numbers a chassis engineer actually uses — ride frequency,
 * damping ratio, bump travel and ride height — because the numbers Rapier wants are
 * derivable from those and the reverse is not. `Vehicle.rebuild` does that
 * conversion (see `wheelSpringRate` below); nothing in this file is a raw rate any
 * more.
 *
 * ---- the algebra that was wrong, and what it cost ----
 *
 * Rapier's ray-cast spring force is `stiffness * compression * chassis_mass`, i.e.
 * the rate is per kilogram of the WHOLE chassis. The body's heave mode therefore
 * stands on all four of those springs at once:
 *
 *     K_total = 4 * k * m     omega = sqrt(K_total / m) = 2 * sqrt(k)
 *
 * This file used to divide by 2*pi after taking `sqrt(k)` alone, missing the factor
 * of two, and every comment in it was wrong by an octave: the "1.06 Hz" saloon was
 * really 2.11 Hz, the "0.87 Hz" truck 1.74 Hz, the "1.33 Hz" fastback 2.66 Hz. The
 * whole catalogue rode between a modern sports car and a racing car, and the same
 * slip put damping at 0.45 and 0.63 of critical rather than the 0.23/0.31 the
 * comments claimed — stiff AND over-damped, which is exactly the "too stiff for no
 * reason" the ride reads as.
 *
 * The critical-damping figure is `2 * sqrt(k * cornerShare)`, and `suspension-probe.ts`
 * checks all of this against a bare Rapier controller so the octave cannot come back.
 *
 * ---- what a period car actually is ----
 *
 * A 1970s saloon runs 1.0-1.3 Hz at the front with the rear 10-20% higher (a rear
 * that rings slightly faster than the front makes the two ends come back into phase
 * as the car drives over a bump instead of pitching — the flat-ride rule, and the
 * reason no real car is sprung evenly). Damping is 0.2-0.3 of critical in
 * compression and 0.35-0.5 in rebound; a rebound-biased damper is what stops a soft
 * spring throwing the body back up. An unladen leaf-sprung pickup is the odd one
 * out: its rear springs are sized for a payload it is not carrying, so it hops.
 *
 * ---- travel, and why a soft spring needs it ----
 *
 * Static deflection follows from the frequency alone: `sag = g / omega^2`, which is
 * 188 mm at 1.15 Hz and 73 mm at 1.85 Hz. Rapier clamps the spring at
 * `rest +/- maxTravel` and a clamp is a rigid stop, so `Vehicle` sizes the travel as
 * `sag + bumpTravel` and puts a progressive bump stop in front of the clamp; the
 * numbers below are that bump travel, not the total.
 *
 * Droop is not a knob: a linear spring extends until it reaches free length, so the
 * available droop is exactly the sag. That is real, and it is why a soft car lifts
 * an inside wheel further.
 */

/** Body heave frequency (Hz) of a per-kilogram rate at a corner carrying `share`. */
export function heaveFrequencyHz(stiffness: number, share: number): number {
  return Math.sqrt(stiffness / share) / (2 * Math.PI);
}

/**
 * The per-kilogram rate that puts a corner carrying `share` of the mass at `hz`.
 * Inverse of `heaveFrequencyHz`; `share` is that wheel's fraction of the sprung
 * weight, so a front-heavy car's front springs come out stiffer for the same
 * frequency, which is what real spring rates do.
 */
export function wheelSpringRate(hz: number, share: number): number {
  const omega = 2 * Math.PI * hz;
  return omega * omega * share;
}

/** The per-kilogram damping coefficient for `ratio` of critical at that corner. */
export function wheelDampingRate(hz: number, ratio: number, share: number): number {
  return 2 * ratio * (2 * Math.PI * hz) * share;
}

/** Fraction of critical damping a per-kilogram coefficient represents. */
export function suspensionDampingRatio(
  stiffness: number,
  damping: number,
  share: number,
): number {
  return damping / (2 * Math.sqrt(stiffness * share));
}

/** Static spring compression (m) at a given ride frequency. Load cancels out. */
export function staticSagM(hz: number): number {
  const omega = 2 * Math.PI * hz;
  return 9.81 / (omega * omega);
}

/**
 * The spring rate in N/m — the rate a real spring HAS — that puts a corner carrying
 * `cornerMassKg` of sprung mass at `hz`.
 *
 * The per-kilogram form above is what Rapier's ray-cast suspension wants, because it
 * multiplies the number it is given by the chassis mass. That makes it useless as a
 * description of a spring: a car with a per-kilogram rate sags to the same ride height
 * empty and loaded, which is the opposite of what a spring does. So the rate is kept
 * in newtons per metre and divided by whatever mass is present at the boundary, and
 * the corner then sits lower and rings slower as it is loaded.
 */
export function wheelSpringRateAbs(hz: number, cornerMassKg: number): number {
  const omega = 2 * Math.PI * hz;
  return omega * omega * cornerMassKg;
}

/** The absolute damping coefficient, N·s/m, for `ratio` of critical at that corner. */
export function wheelDampingRateAbs(hz: number, ratio: number, cornerMassKg: number): number {
  const omega = 2 * Math.PI * hz;
  return 2 * ratio * omega * cornerMassKg;
}

/**
 * The everyday saloon: 1.15 Hz front, 1.32 Hz rear. Sag 188/143 mm, and a soft
 * damper that lets the body take a set before it comes back.
 */
const SUSP_CAR: SuspensionTuning = {
  frontHz: 1.15,
  rearHz: 1.32,
  compressionRatio: 0.26,
  reboundRatio: 0.42,
  bumpTravel: 0.09,
  frontRollCentreM: 0.08,
  rearRollCentreM: 0.3,
  frontBar: 1,
  rearBar: 0,
  ackermann: 0.6,
  frontCamberDeg: 0,
  rearCamberDeg: 0,
  frontRollCamber: 0.7,
  rearRollCamber: 0,
  frontToeDeg: 0.05,
  rearToeDeg: 0,
  frontRollSteer: 0.04,
  rearRollSteer: 0.06,
  frontCasterDeg: 2,
};

/* ---- the Soviet families ----
 *
 * One SOFT preset used to carry eleven cars, which is why they all rode the same:
 * a Volga on leaf springs and 15-inch balloon tyres, a Fiat-derived Zhiguli, a
 * MacPherson-strut Samara from 1984 and a long-travel Niva are four different
 * chassis, and the ride frequency is where that difference lives.
 *
 * Every figure below is what the real suspension measures, and the ladder is the
 * real one: the Volga is the softest thing in the catalogue, the Zhigulis sit at
 * the period saloon norm, the payload-sprung estates ring hard at the back, the
 * Samara is a decade newer and firmer at both ends, and the Niva trades frequency
 * for travel rather than for softness.
 */

/*
 * `Vehicle.rebuild` adds one sixth of the measured wheel radius to the catalogue's
 * clearance before placing the contact plane. The numbers in `FACTORY_GEOMETRY` are
 * therefore BASE clearances, already reduced by that measured lift: the suspension
 * probe then reads 144-224 mm under a settled body, the Niva highest and the
 * AZLK-2141 lowest. Writing those real figures directly made every car sit 50-63 mm
 * too high.
 */

/*
 * ---- roll: roll centres and bars ----
 *
 * The roll centres are the linkage's, read off the layout rather than tuned: parallel
 * wishbones (Volga, Zhiguli, Niva fronts) and MacPherson struts (Samara family) put the
 * front one 0.07-0.12 m off the road; a live axle puts the rear one at its Panhard rod
 * (Zhiguli, Niva, ~0.3-0.4 m) or its leaf-spring seats (Volga, the pickup, ~0.36-0.4 m);
 * a twist beam sits between the two (Samara family, 0.12 m). A high rear roll centre
 * sends that axle more of the transfer, which is why a live-axle car needs the
 * front-heavy bar it has to stay an understeerer.
 *
 * The bars are the knob, and they are set so a saloon leans 3.5-5 degrees per g, the
 * soft Volgas and the tall Niva and van more, and every car keeps the front-biased
 * transfer that makes it run out of grip at the nose first (tools/roll-balance.ts).
 * The Samara family's rear figure is its twist beam. A NEGATIVE figure is a beam axle
 * on leaf springs: the leaves hang under the frame rails, well inboard of the wheels,
 * so the axle resists roll by `(spring spacing / track)²` of its ride rate, not all of
 * it.
 */

/*
 * ---- steering and wheel geometry ----
 *
 * Alignment is the factory sheet's where one exists: a Zhiguli or Niva runs +0°30′ of
 * camber and 2-4 mm of toe-in at the rim (VAZ-2101 manual, sec. 8.1.3), a Volga 0°±30′
 * and 1.5-3 mm at the tyre (GAZ-24 manual), a Samara or 2110 0°±30′ and 0±1 mm. The
 * toe figures below are the BOTTOM of each range, converted at the diameter it is
 * measured across (`SuspensionTuning.frontToeDeg`): the top of it is set to cancel the
 * toe-out rolling drag pulls through the bushes, and the model has no bushes.
 *
 * Roll camber and roll steer follow the linkage: a beam axle keeps its wheels square to
 * the road (roll camber 0), unequal wishbones keep ~0.6 of the body's lean, a strut
 * ~0.8, a twist beam with its cross member near the pivots ~0.75. Roll steer is the
 * mild understeer every period chassis was given: ~0.04 °/° at the front from the
 * tie-rod geometry, 0.05-0.06 from a live axle's four links, ~0.1 from leaf springs,
 * whose eyes and shackles swing the axle as it rolls (Gillespie, Fundamentals of
 * Vehicle Dynamics, ch. 8). Ackermann is the trapezoid's share of the ideal, 0.5-0.8:
 * no maker in the catalogue published it, so these are the layout's usual figures.
 *
 * Caster is the factory sheet's too: +3°30′ on the Zhiguli and Niva wishbones, +1°30′
 * on the Samara family's struts, about +0°30′ on the Volgas' kingpins, +3° on a beam
 * front. It only reaches the steering (`SuspensionTuning.frontCasterDeg`): a Zhiguli's
 * wheel pulls back to centre noticeably harder than a Volga's.
 */

/**
 * GAZ-21: 0.95 Hz front on 240 mm of sag, a LEAF-sprung rear at 1.15 Hz, and
 * lever-arm dampers that were marginal when new (0.18/0.30 of critical). It floats,
 * takes a set slowly and keeps moving after the road has stopped — and that motion
 * IS the load transfer, which is what makes its breakaway progressive and its
 * cornering limit low. 190 mm of clearance, because it was built for Soviet roads.
 */
const SUSP_VOLGA_21: SuspensionTuning = {
  frontHz: 0.95,
  rearHz: 1.15,
  compressionRatio: 0.18,
  reboundRatio: 0.3,
  bumpTravel: 0.1,
  frontRollCentreM: 0.1,
  rearRollCentreM: 0.38,
  frontBar: 1.6,
  rearBar: -0.4,
  ackermann: 0.7,
  frontCamberDeg: 0,
  rearCamberDeg: 0,
  frontRollCamber: 0.6,
  rearRollCamber: 0,
  // 1.5 mm at a 6.70-15 tyre (0.72 m).
  frontToeDeg: 0.06,
  rearToeDeg: 0,
  frontRollSteer: 0.04,
  rearRollSteer: 0.1,
  frontCasterDeg: 0.5,
};

/** GAZ-24: the same layout fifteen years later, with dampers that work. */
const SUSP_VOLGA_24: SuspensionTuning = {
  frontHz: 1.0,
  rearHz: 1.22,
  compressionRatio: 0.2,
  reboundRatio: 0.34,
  bumpTravel: 0.1,
  frontRollCentreM: 0.1,
  rearRollCentreM: 0.36,
  frontBar: 1.4,
  rearBar: -0.4,
  ackermann: 0.7,
  frontCamberDeg: 0,
  rearCamberDeg: 0,
  frontRollCamber: 0.6,
  rearRollCamber: 0,
  frontToeDeg: 0.06,
  rearToeDeg: 0,
  frontRollSteer: 0.04,
  rearRollSteer: 0.1,
  frontCasterDeg: 0.5,
};

/**
 * The Zhiguli saloons. Coils at both ends, a live rear axle on four links and a
 * Panhard rod: a 1966 Fiat chassis, so FIRMER and better damped than anything else
 * the USSR built in the sixties — 1.10 Hz front, 1.28 rear, and the flat-ride
 * relationship between them that keeps it from pitching.
 */
const SUSP_ZHIGULI: SuspensionTuning = {
  frontHz: 1.1,
  rearHz: 1.28,
  compressionRatio: 0.24,
  reboundRatio: 0.38,
  bumpTravel: 0.095,
  frontRollCentreM: 0.08,
  rearRollCentreM: 0.3,
  frontBar: 1.5,
  rearBar: 0,
  ackermann: 0.6,
  frontCamberDeg: 0.5,
  rearCamberDeg: 0,
  frontRollCamber: 0.6,
  rearRollCamber: 0,
  // 2 mm across a 13-inch rim's flanges (0.36 m).
  frontToeDeg: 0.16,
  rearToeDeg: 0,
  frontRollSteer: 0.04,
  rearRollSteer: 0.06,
  frontCasterDeg: 3.5,
};

/**
 * The 2102/2104 estates: rear springs rated for 430 kg of cargo that is not in the
 * back, so the tail rings at 1.55 Hz against the front's 1.10. Empty, it skips over
 * sharp bumps and steps out on a rough bend — the same mechanism as the empty
 * pickup, on a car that looks like a saloon.
 */
const SUSP_ZHIGULI_ESTATE: SuspensionTuning = {
  frontHz: 1.1,
  rearHz: 1.55,
  compressionRatio: 0.24,
  reboundRatio: 0.4,
  bumpTravel: 0.09,
  frontRollCentreM: 0.08,
  rearRollCentreM: 0.3,
  frontBar: 1.5,
  rearBar: 0,
  ackermann: 0.6,
  frontCamberDeg: 0.5,
  rearCamberDeg: 0,
  frontRollCamber: 0.6,
  rearRollCamber: 0,
  frontToeDeg: 0.16,
  rearToeDeg: 0,
  frontRollSteer: 0.04,
  rearRollSteer: 0.06,
  frontCasterDeg: 3.5,
};

/**
 * Samara: MacPherson struts in front, a trailing-arm torsion beam behind, and the
 * first Soviet car with dampers matched to its springs. 1.30/1.55 Hz and 0.28/0.42
 * of critical — firm for the pack, ordinary for 1984, and the reason it turns in
 * instead of leaning first.
 */
const SUSP_SAMARA: SuspensionTuning = {
  frontHz: 1.3,
  rearHz: 1.55,
  compressionRatio: 0.28,
  reboundRatio: 0.42,
  bumpTravel: 0.085,
  frontRollCentreM: 0.07,
  rearRollCentreM: 0.12,
  frontBar: 1.2,
  rearBar: 0.6,
  ackermann: 0.5,
  frontCamberDeg: 0,
  rearCamberDeg: 0,
  frontRollCamber: 0.8,
  rearRollCamber: 0.75,
  frontToeDeg: 0,
  rearToeDeg: 0,
  frontRollSteer: 0.04,
  rearRollSteer: 0.03,
  frontCasterDeg: 1.5,
};

/**
 * Niva: coils on all four corners with 200 mm of wheel travel and 220 mm under the
 * floor. It is NOT a leaf-sprung truck — that was the old tuning's mistake, and it
 * gave the car a 1.85 Hz rear that hopped. A Niva's rear rings barely faster than
 * its front (1.20 against 1.15) and pays for its ground clearance in TRAVEL, which
 * is what lets it keep four tyres on a surface a saloon skates over.
 */
const SUSP_NIVA: SuspensionTuning = {
  frontHz: 1.15,
  rearHz: 1.2,
  compressionRatio: 0.24,
  reboundRatio: 0.4,
  bumpTravel: 0.14,
  frontRollCentreM: 0.12,
  rearRollCentreM: 0.4,
  frontBar: 1,
  rearBar: 0,
  ackermann: 0.6,
  frontCamberDeg: 0.5,
  rearCamberDeg: 0,
  frontRollCamber: 0.6,
  rearRollCamber: 0,
  // 2 mm across a 16-inch rim's flanges (0.43 m).
  frontToeDeg: 0.13,
  rearToeDeg: 0,
  frontRollSteer: 0.04,
  rearRollSteer: 0.06,
  frontCasterDeg: 3.5,
};

/**
 * The rally 2105: uprated springs, gas dampers, long travel and 5 cm of extra
 * stance, because a rally car is raised, not lowered. 1.55/1.75 Hz.
 */
const SUSP_LADA_RALLY: SuspensionTuning = {
  frontHz: 1.55,
  rearHz: 1.75,
  compressionRatio: 0.32,
  reboundRatio: 0.48,
  bumpTravel: 0.12,
  frontRollCentreM: 0.08,
  rearRollCentreM: 0.3,
  frontBar: 1,
  rearBar: 0,
  // A gravel build: negative camber, no toe and less Ackermann than the road car.
  ackermann: 0.4,
  frontCamberDeg: -1,
  rearCamberDeg: 0,
  frontRollCamber: 0.6,
  rearRollCamber: 0,
  frontToeDeg: 0,
  rearToeDeg: 0,
  frontRollSteer: 0.03,
  rearRollSteer: 0.05,
  frontCasterDeg: 3.5,
};

/**
 * SOFT: the rear-engined vans and buses, which are sprung for a load they are not
 * carrying at the wrong end of the car. The least damped preset in the catalogue,
 * so the body leans, wallows and takes its set slowly.
 *
 * It used to carry the entire Soviet pack as well. It no longer does: those cars
 * have their own families above, because a leaf-sprung Volga, a Fiat-derived
 * Zhiguli, a strut-front Samara and a long-travel Niva were never one spring rate.
 */
const SUSP_SOFT: SuspensionTuning = {
  frontHz: 1.02,
  rearHz: 1.18,
  compressionRatio: 0.22,
  reboundRatio: 0.36,
  bumpTravel: 0.1,
  frontRollCentreM: 0.1,
  rearRollCentreM: 0.2,
  frontBar: 0.6,
  rearBar: 0,
  ackermann: 0.6,
  frontCamberDeg: 0,
  rearCamberDeg: 0,
  frontRollCamber: 0.7,
  rearRollCamber: 0.8,
  frontToeDeg: 0.05,
  rearToeDeg: 0,
  frontRollSteer: 0.03,
  rearRollSteer: 0,
  frontCasterDeg: 2,
};

/** "Sport" in this era means a firm saloon on stiffer dampers, not a modern chassis. */
const SUSP_SPORT: SuspensionTuning = {
  frontHz: 1.38,
  rearHz: 1.55,
  compressionRatio: 0.3,
  reboundRatio: 0.46,
  bumpTravel: 0.08,
  frontRollCentreM: 0.06,
  rearRollCentreM: 0.25,
  frontBar: 1.2,
  rearBar: 0.3,
  ackermann: 0.5,
  frontCamberDeg: -0.5,
  rearCamberDeg: 0,
  frontRollCamber: 0.6,
  rearRollCamber: 0,
  frontToeDeg: 0,
  rearToeDeg: 0,
  frontRollSteer: 0.04,
  rearRollSteer: 0.05,
  frontCasterDeg: 3,
};

/**
 * Unladen leaf-sprung working vehicle. The rear is sprung for a payload that is not
 * in the bed, so it rings at 1.85 Hz against the front's 1.3 and skips over sharp
 * bumps — the empty-pickup hop, and the reason the tail steps out on a rough bend.
 */
const SUSP_TRUCK: SuspensionTuning = {
  frontHz: 1.3,
  rearHz: 1.85,
  compressionRatio: 0.24,
  reboundRatio: 0.38,
  bumpTravel: 0.11,
  frontRollCentreM: 0.1,
  rearRollCentreM: 0.4,
  frontBar: 1,
  rearBar: -0.4,
  ackermann: 0.7,
  frontCamberDeg: 0.5,
  rearCamberDeg: 0,
  frontRollCamber: 0.6,
  rearRollCamber: 0,
  frontToeDeg: 0.06,
  rearToeDeg: 0,
  frontRollSteer: 0.04,
  rearRollSteer: 0.1,
  frontCasterDeg: 3,
};

/* ---- weight distribution ----
 *
 * Where the mass sits along the wheelbase, as a fraction on the FRONT axle. It is
 * not a tuning knob: for a front-engined car it follows from the layout, and it is
 * the single most load-bearing number in the car's balance, because every axle load,
 * spring rate, load-sensitivity reference and transfer calculation is measured
 * against it. `Vehicle` turns it into the chassis' centre of mass and each wheel's
 * static load using the model's own axle positions.
 *
 * The figures are period kerb measurements:
 *
 *   front-engine RWD saloon      52-55% front   (engine ahead of the axle, live
 *                                                axle and tank behind)
 *   transverse FWD hatchback     60-63% front   (engine, box and diff all on the
 *                                                front axle; nothing over the rear)
 *   part-time 4WD wagon/off-road 55-57% front   (a transfer case adds mass amidships)
 *   working vehicle, empty bed   56-58% front   (the payload it is sprung for is
 *                                                not in it — the empty-pickup case)
 *
 * `frontWeightShare` overrides those defaults for bodies whose engine is not over
 * the axle the drive bias implies. Drive bias cannot distinguish a front-engine
 * RWD car from a rear-engine one, and treating both as 53% front makes the latter
 * rotate around an axle it does not actually load.
 */
export function frontWeightFraction(model: {
  readonly rearDriveBias: number;
  readonly bodyClass: BodyClass;
  readonly frontWeightShare?: number;
}): number {
  if (model.frontWeightShare !== undefined) return model.frontWeightShare;
  if (model.bodyClass === 'truck' || model.bodyClass === 'bus') return 0.57;
  // Drive bias is the fallback layout: 0 is transverse front-drive, 1 is a front
  // engine driving the back axle, and a half is four-wheel drive.
  if (model.rearDriveBias <= 0.01) return 0.62;
  if (model.rearDriveBias >= 0.99) return 0.53;
  return 0.56;
}

/**
 * Authored lamp selectors. A selector names a mesh node or material carrying one
 * independently controlled lamp channel. Normalized models provide those meshes
 * directly, so their bounds locate the light source without inspecting triangles
 * or treating an entire body as one lens.
 */
export interface VehicleLightsDef {
  readonly headlights: readonly string[];
  /** Running-light lenses; models with combined rear lenses omit `brakeLights`. */
  readonly taillights: readonly string[];
  /** Dedicated stop-lamp lenses when braking does not use the running-light section. */
  readonly brakeLights?: readonly string[];
  readonly reverseLights?: readonly string[];
  readonly leftBlinkers?: readonly string[];
  readonly rightBlinkers?: readonly string[];
}

/**
 * The model's own node names for the four wheels the vehicle drives, when the pack
 * names them consistently. Naming them beats finding them by shape: a normalized
 * GTA SA body draws each wheel as a tyre plus a separate hub island, and shape
 * detection would mount the tyres alone and leave the hubs standing in the body.
 *
 * A wheel may name several nodes for a body that draws one wheel as a hub plus a
 * tyre; they are detached together and spin as one.
 */
export interface WheelNodeNames {
  readonly wheel_fl: readonly string[];
  readonly wheel_fr: readonly string[];
  readonly wheel_rl: readonly string[];
  readonly wheel_rr: readonly string[];
}

/** Geometry metadata needed before the visual asset itself is resident. */
export interface CarModelFit {
  readonly halfExtents: readonly [number, number, number];
  readonly wheels: readonly {
    readonly id: string;
    readonly pos: readonly [number, number, number];
    readonly radius: number;
    readonly isFront: boolean;
  }[];
  readonly hoodPoint: readonly [number, number, number];
  readonly visualOffset: readonly [number, number, number];
}
/** Stock exterior and running-gear dimensions, metres. */
export interface FactoryGeometry {
  readonly length: number;
  readonly width: number;
  readonly height: number;
  /** Minimum published ground clearance. */
  readonly clearance: number;
  readonly wheelbase: number;
  readonly frontTrack: number;
  readonly rearTrack: number;
  readonly wheelRadius: number;
  readonly tyreWidth: number;
  /** Nose to front axle; set when source-art axle bias disagrees with factory drawings. */
  readonly frontOverhang?: number;
}


/**
 * A limited-slip differential, as the two numbers its makers quote. It may hold the
 * two wheels of its axle apart in speed with at most `preloadNm` plus `lock` times the
 * torque going through it; anything beyond slips, as an open differential always does.
 *
 *   clutch pack (Salisbury, ZF, Traction-Lok)  preload 50-150 Nm, lock 0.25-0.45
 *   Torsen (torque-sensing gears)              preload 0, lock 0.5-0.6: open when
 *                                              one wheel carries nothing at all
 *   welded or spool                            lock 1 and a preload nothing reaches
 *
 * `lock` is (TBR - 1) / (TBR + 1) for a quoted torque bias ratio.
 */
export interface LimitedSlip {
  readonly lock: number;
  readonly preloadNm: number;
}

/**
 * The tyre the car was sold on, as its size is written on the sidewall. The side-force
 * curve is derived from it (`tyreCurve` in vehicletuning.ts): a tall soft sidewall
 * builds force slowly, peaks late and lets go gently; a low radial is quick, peaks
 * early and breaks away more sharply.
 */
export interface TyreSpec {
  readonly construction: 'crossply' | 'radial';
  /** Sidewall height over section width: 0.82 for 165R13, 0.6 for 225/60. */
  readonly aspect: number;
}

/** Mechanical era shared by cars with the same steering and tyre construction. */
export type HandlingProfile = 'classic' | 'road' | 'sport' | 'utility';

/**
 * A body's aerodynamics beyond its drag area: what the air does to it vertically and
 * sideways. Every coefficient is on `frontalArea` and the dynamic pressure ½ρV² of the
 * air relative to the car, in the wind-tunnel conventions the period literature quotes
 * them in (Hucho, Aerodynamics of Road Vehicles), so a figure from a book goes in as
 * printed. The vehicle turns them into forces in `Vehicle.applyAero`.
 *
 *   liftFront/Rear  the load each axle's wheel pads LOSE, over q·A, positive up; their
 *                   sum is the car's CL. A tunnel's pads hold the car at the road, so
 *                   the drag's own nose-up moment about the road is inside this split
 *                   (the vehicle takes it back out, because it applies the drag at its
 *                   own height). Period saloons run CL 0.3-0.45, the rear axle usually
 *                   the lighter one; a squareback estate or van has little rear lift
 *                   (the flow separates at the roof's end instead of curving down a
 *                   tail), a blunt-nosed one more front lift.
 *   sideSlope       dCY/dβ per radian of the side force's linear (slender-body) part,
 *                   which `Vehicle.applyAero` scales by sinβ·cosβ. The flank's crossflow
 *                   drag (CROSSFLOW_CD in vehicle.ts) adds the progressive part on top,
 *                   so the slope is chosen for the SUM to land where tunnels measure it:
 *                   CY ≈ 0.7 at β = 20° for a saloon (0.035 per degree, near enough
 *                   linear), about 0.9 for a tall box. 1.25-1.55 for cars, 1.6-1.9 for
 *                   estates, off-roaders and vans.
 *   yawSlope        dCN/dβ per radian of that same linear part, on A times the
 *                   wheelbase, about the wheelbase's midpoint; positive turns the nose
 *                   DOWNWIND. yawSlope / sideSlope is how far ahead of the midpoint the
 *                   linear part acts, in wheelbases: a third for cars (the reason a
 *                   crosswind steers a car out of it), less for a squareback, whose
 *                   tall rear flank draws it aft. The crossflow part acts at the body's
 *                   middle, so the centre of pressure moves back as the yaw grows.
 *
 * No Soviet body has a published lift or crosswind figure. The values below are the
 * literature's for the same SHAPE — notchback, fastback, squareback, two-box, van —
 * scaled to frontal areas from AvtoVAZ's own figures where they exist (Samara 1.87 m²,
 * Oka 1.69, Niva about 2.4) and from width × body height × 0.85 elsewhere.
 */
export interface AeroSpec {
  /** Frontal area A, m²: the reference area of every coefficient here. */
  readonly frontalArea: number;
  readonly liftFront: number;
  readonly liftRear: number;
  readonly sideSlope: number;
  readonly yawSlope: number;
}

/** GAZ-21: the rounded fifties saloon, its long tail curving down; the most lift. */
const AERO_VOLGA_21: AeroSpec = { frontalArea: 2.1, liftFront: 0.2, liftRear: 0.25, sideSlope: 1.35, yawSlope: 0.5 };
/** GAZ-24: a square three-box saloon. */
const AERO_VOLGA_24: AeroSpec = { frontalArea: 2.15, liftFront: 0.14, liftRear: 0.2, sideSlope: 1.5, yawSlope: 0.45 };
/** The Fiat-124 Zhiguli saloons, 2101 to 2107. */
const AERO_ZHIGULI: AeroSpec = { frontalArea: 1.8, liftFront: 0.13, liftRear: 0.22, sideSlope: 1.4, yawSlope: 0.47 };
/** The 2102/2104 estates: square back, so little rear lift and a centre of pressure further aft. */
const AERO_ZHIGULI_ESTATE: AeroSpec = { frontalArea: 1.84, liftFront: 0.17, liftRear: 0.08, sideSlope: 1.6, yawSlope: 0.33 };
/** Samara hatchbacks: the wedge nose holds the front down, the hatch lifts the rear. */
const AERO_SAMARA_HATCH: AeroSpec = { frontalArea: 1.87, liftFront: 0.08, liftRear: 0.26, sideSlope: 1.25, yawSlope: 0.5 };
/** 21099: the Samara nose on a short notched boot. */
const AERO_SAMARA_SALOON: AeroSpec = { frontalArea: 1.87, liftFront: 0.09, liftRear: 0.21, sideSlope: 1.35, yawSlope: 0.47 };
/** Niva: a blunt two-box off-roader, tall and short. */
const AERO_NIVA: AeroSpec = { frontalArea: 2.4, liftFront: 0.2, liftRear: 0.12, sideSlope: 1.7, yawSlope: 0.37 };
/** AZLK-2141: a liftback in the Simca 1307's shape. */
const AERO_AZLK_2141: AeroSpec = { frontalArea: 1.95, liftFront: 0.1, liftRear: 0.24, sideSlope: 1.25, yawSlope: 0.5 };
/** Oka: a short, tall two-box hatch. */
const AERO_OKA: AeroSpec = { frontalArea: 1.69, liftFront: 0.14, liftRear: 0.16, sideSlope: 1.55, yawSlope: 0.47 };
/** UAZ-330364: a cab-over flatbed; the flow leaves the flat cab front and roof, the bed sits in the wake. */
const AERO_UAZ_330364: AeroSpec = { frontalArea: 3.8, liftFront: 0.25, liftRear: 0, sideSlope: 1.9, yawSlope: 0.2 };
/** IZH-2715: a Moskvich nose on a square van box. */
const AERO_IZH_2715: AeroSpec = { frontalArea: 2.35, liftFront: 0.2, liftRear: 0.02, sideSlope: 1.8, yawSlope: 0.27 };
/** VAZ-2110: a nineties saloon shaped in the tunnel, Cd 0.33. */
const AERO_VAZ_2110: AeroSpec = { frontalArea: 2.05, liftFront: 0.08, liftRear: 0.17, sideSlope: 1.35, yawSlope: 0.44 };
/**
 * UAZ-3151 family: a flat-faced two-box off-roader, taller and longer than the Niva,
 * so the Niva's shape figures on its own 1.785 m × (2.02 − 0.22) m × 0.85 frontal area.
 */
const AERO_UAZ_3151: AeroSpec = { frontalArea: 2.75, liftFront: 0.2, liftRear: 0.1, sideSlope: 1.8, yawSlope: 0.33 };




export interface CarModelDef {
  /** Stable id; appears in save files. */
  readonly id: string;
  readonly label: string;
  /** Model URL (.glb or .fbx), served from public/. */
  readonly file: string;
  /** Static geometry metadata; lets physics and POI layout precede visual streaming. */
  readonly fit: CarModelFit;
  /**
   * Base-colour texture URL, when the pack ships its palette separately from the
   * geometry. Both packs do, so the map is loaded once per pack and shared.
   */
  readonly textureFile?: string;
  /**
   * How this pack encodes body colour. Soviet bodies select a solid swatch from a
   * shared 9x2 atlas, replaced in the fragment shader; the GTA SA conversions ship
   * flat runtime materials whose paint slots are recoloured outright.
   */
  readonly paintStyle?: 'soviet-atlas' | 'solid-paint';
  /** Paint material that receives a deterministic contrasting colour. */
  readonly secondaryPaintMaterial?: string;
  /** Original Soviet body-paint cell, in the FBX UV coordinate system. */
  readonly paintUvCell?: readonly [number, number];
  /**
   * The window glass, which the two packs encode incompatibly.
   *
   * A normalized GTA SA body draws its windows as separate meshes sharing one
   * authored `car_glass` material, so naming that material is enough. A Soviet body
   * has no window objects at all: its glass is a REGION OF ONE MESH whose UVs point
   * at a single atlas swatch, so the loader cuts those triangles out into their own
   * mesh (`isolateGlass` in render/carmodel.ts).
   *
   * Set one or the other, never both.
   */
  readonly glassMaterial?: string;
  readonly glassUvCell?: readonly [number, number];
  /**
   * Material this body's REAR SCREEN is drawn with when the pack did not draw it as
   * glass: GTA SA models often leave the tailgate's opening empty and author the piece
   * behind it as a trim plate, which reads as a window and is aimed at like one but is
   * neither glass nor paint anywhere downstream. `sa_oka` is one, on `car_trim`.
   *
   * `buildTemplate` then cuts the plate that closes the opening out of that material's
   * mesh into the glass (`glassOverTailOpening` in render/carmodel.ts), so the window
   * mirrors, gathers dust and takes stickers like every other window. The pack's own
   * contract is that windows ship as `car_glass` — see `tools/dff-pack-import.md`.
   */
  readonly rearScreenMaterial?: string;
  /** Factory geometry used to fit body, axles and tyres at load time. */
  readonly factory: FactoryGeometry;
  /**
   * Candidate road Soviet wheel-set model ids. The selected source supplies style
   * only; this car's own factory radius and axle positions remain authoritative.
   */
  readonly wheelSetPool?: readonly string[];
  /**
   * Loaded visual settle in metres. Applied only to the sprung body; axle centres
   * stay fixed and connected suspension geometry deforms continuously.
   */
  readonly loadedRideDrop?: number;
  /**
   * Set when the model carries its own wheels but under the modeller's names
   * (`Wheel_1`, `Cylinder006`, ...). The loader then finds the four discs by shape
   * and renames them to the convention.
   */
  readonly detectWheels?: boolean;
  /** Set instead of `detectWheels` when the pack names its wheels consistently. */
  readonly wheelNodes?: WheelNodeNames;
  readonly bodyClass: BodyClass;
  /** Uniform model-units-to-metres scale. */
  readonly scale: number;
  /**
   * Yaw applied to the imported model before it is measured, radians.
   *
   * The game drives toward +Z, so a model authored nose-first down -Z arrives
   * back to front: it drives in reverse and its front axle steers from the rear.
   * Nothing in a model file declares which end the lights are on — a body is just a
   * mesh — so this is authored per pack. Both shipped packs are nose-first down +Z
   * and set nothing.
   *
   * It is applied before measurement rather than at draw time on purpose. Every
   * derived quantity — the chassis box, which axle is the front one and the bonnet
   * camera mount — comes out of the measured geometry, so rotating the geometry first is
   * what keeps all of them agreeing with each other.
   */
  readonly yaw?: number;
  /** Kerb mass, kg. Complete vehicle — there are no parts left to add to it. */
  readonly mass: number;
  /** Engine and gearbox, by part-variant id, so the specs live in one table. */
  readonly engineId: string;
  readonly gearboxId: string;
  readonly tankLitres: number;
  /** Tyre grip multiplier on the surface's friction, in every direction alike. */
  readonly wheelGrip: number;
  /**
   * What the car's own brakes deliver at a FLOORED pedal (a panic stamp) on a surface
   * that does not limit them, in g: the drums, discs and servo, not the tyres. Every
   * car here could lock its wheels on dry asphalt, so every figure is above its tyres'
   * peak and a floored pedal locks; the stopping distance is then the tyre's
   * (`wheelGrip`, the surface, the sliding plateau), as it was on the real cars.
   *
   * The floor under these figures is the Soviet type approval: GOST 22895-77 held a
   * passenger car to 43.2 m from 80 km/h at gross mass with a 50 kgf pedal
   * (https://poznayka.org/s80171t2.html), i.e. at least 0.58 g at half a panic stamp's
   * force even before the brakes' response time is taken off. A floored pedal is
   * about twice that force, so the hydraulics alone reach past 1 g; a vacuum servo
   * takes it further. Unassisted cars are 1.0, servo cars 1.2: the exact figure
   * decides only where on the pedal the lock begins, not how far the car stops.
   *
   * It used to be a stopping-distance target in disguise, 0.42-0.6 g, sized to unsourced
   * "period 100-0 tests" in `tools/reality.ts`: below the tyres, so a held pedal never
   * locked anything (74 m from 100 km/h in a Zhiguli) and every road car failed its
   * own type approval.
   */
  readonly brakeDecelG: number;
  readonly suspension: SuspensionTuning;
  /**
   * Steering lock, radians: the rack's angle, the bicycle-model angle of the front
   * axle's centreline. The inner wheel turns further and the outer less, by the
   * suspension's Ackermann share (see the steering-lock note above the Soviet specs).
   */
  readonly steerLock: number;
  /** Fraction of drive torque to the rear axle. 1 = RWD, 0 = FWD, 0.5 = 4WD. */
  readonly rearDriveBias: number;
  /**
   * Steering, tyre and driveline character. `classic` preserves the Soviet model;
   * later radial-tyred cars and working vehicles use their own mechanisms.
   */
  readonly handlingProfile: HandlingProfile;
  /** Static share of kerb weight carried by the front axle, when layout needs an override. */
  readonly frontWeightShare?: number;
  /**
   * Anti-roll bars, each as a fraction of its own axle's wheel rate (0 = no bar), when
   * the car's are not its suspension preset's (`SuspensionTuning.frontBar`/`rearBar`).
   * The split is the handling balance: the axle with more roll stiffness takes more of
   * the load transfer and runs out of grip first.
   */
  readonly antiRoll?: { readonly front: number; readonly rear: number };
  /**
   * Roll-centre heights above the road, metres, when the car's linkage is not its
   * suspension preset's (`SuspensionTuning.frontRollCentreM`/`rearRollCentreM`): a beam
   * front axle on a preset written for wishbones, say.
   */
  readonly rollCentre?: { readonly front: number; readonly rear: number };
  /** The factory tyre, when the car's own curve should replace the profile's. */
  readonly tyre?: TyreSpec;
  /**
   * A limited-slip differential on that axle; absent is an open one. See
   * `LimitedSlip`. Only meaningful on a driven axle.
   */
  readonly frontDiff?: LimitedSlip;
  readonly rearDiff?: LimitedSlip;
  /**
   * The body's drag area, Cd·A in m². Authored where the real car's is known; a
   * body that omits it falls back to one shared Cd over its measured box, which
   * only lands for a mid-seventies saloon shape (see `Vehicle`'s constructor).
   */
  readonly dragArea?: number;
  /** Lift and crosswind: see `AeroSpec`. */
  readonly aero: AeroSpec;
  /** Authored lenses whose per-instance materials mirror the vehicle's live controls. */
  readonly lights?: VehicleLightsDef;
  /** Every car body carries the shared 4x2 trunk. */
  readonly storageCells: number;
}

/** Shared defaults; every entry below states only what makes it itself. */
type Entry = Omit<
  CarModelDef,
  | 'file'
  | 'fit'
  | 'factory'
  | 'scale'
  | 'suspension'
  | 'lights'
  | 'storageCells'
  | 'handlingProfile'
> & {
  /** Model file name within the pack directory named by `dir`. */
  readonly glb: string;
  /** Directory containing `glb`. */
  readonly dir: string;
  readonly scale?: number;
  readonly suspension?: SuspensionTuning;
  readonly handlingProfile?: HandlingProfile;
  readonly lights?: VehicleLightsDef;
  /** Legacy authored hint; the catalogue normalizer now gives every body eight cells. */
  readonly storageCells?: number;
};

/**
 * Historical stock dimensions. Metric tyre radii come from the listed factory
 * sizes; the three old inch-size vehicles retain their measured period-tyre radii.
 * The 2105 rally keeps its 0.300 m competition tyre on the stock 2105 shell.
 */
const FACTORY_GEOMETRY: Readonly<Record<string, FactoryGeometry>> = {
  sv_gaz21:       { length: 4.830, width: 1.800, height: 1.620, clearance: 0.190, wheelbase: 2.700, frontTrack: 1.410, rearTrack: 1.420, wheelRadius: 0.365, tyreWidth: 0.170 },
  sv_gaz24:       { length: 4.735, width: 1.800, height: 1.490, clearance: 0.174, wheelbase: 2.800, frontTrack: 1.470, rearTrack: 1.420, wheelRadius: 0.354, tyreWidth: 0.187 },
  sv_vaz2101:     { length: 4.073, width: 1.611, height: 1.382, clearance: 0.170, wheelbase: 2.424, frontTrack: 1.349, rearTrack: 1.305, wheelRadius: 0.297, tyreWidth: 0.155 },
  sv_vaz2102:     { length: 4.059, width: 1.611, height: 1.458, clearance: 0.170, wheelbase: 2.424, frontTrack: 1.365, rearTrack: 1.321, wheelRadius: 0.297, tyreWidth: 0.165 },
  sv_vaz2103:     { length: 4.116, width: 1.611, height: 1.446, clearance: 0.170, wheelbase: 2.424, frontTrack: 1.365, rearTrack: 1.321, wheelRadius: 0.288, tyreWidth: 0.165 },
  sv_vaz2104:     { length: 4.115, width: 1.620, height: 1.443, clearance: 0.170, wheelbase: 2.424, frontTrack: 1.365, rearTrack: 1.321, wheelRadius: 0.288, tyreWidth: 0.165 },
  sv_vaz2105:     { length: 4.130, width: 1.620, height: 1.446, clearance: 0.170, wheelbase: 2.424, frontTrack: 1.365, rearTrack: 1.321, wheelRadius: 0.288, tyreWidth: 0.165 },
  sv_vaz2105r:    { length: 4.130, width: 1.620, height: 1.446, clearance: 0.170, wheelbase: 2.424, frontTrack: 1.365, rearTrack: 1.321, wheelRadius: 0.300, tyreWidth: 0.185 },
  sv_vaz2106:     { length: 4.166, width: 1.611, height: 1.444, clearance: 0.170, wheelbase: 2.424, frontTrack: 1.365, rearTrack: 1.321, wheelRadius: 0.288, tyreWidth: 0.165 },
  sv_vaz2107:     { length: 4.128, width: 1.620, height: 1.435, clearance: 0.170, wheelbase: 2.424, frontTrack: 1.365, rearTrack: 1.321, wheelRadius: 0.288, tyreWidth: 0.165 },
  sv_vaz2108:     { length: 4.006, width: 1.650, height: 1.402, clearance: 0.170, wheelbase: 2.460, frontTrack: 1.400, rearTrack: 1.370, wheelRadius: 0.281, tyreWidth: 0.165 },
  sv_vaz2109:     { length: 4.006, width: 1.650, height: 1.402, clearance: 0.160, wheelbase: 2.460, frontTrack: 1.400, rearTrack: 1.370, wheelRadius: 0.281, tyreWidth: 0.165 },
  sv_vaz21099:    { length: 4.205, width: 1.650, height: 1.402, clearance: 0.160, wheelbase: 2.460, frontTrack: 1.400, rearTrack: 1.370, wheelRadius: 0.281, tyreWidth: 0.165 },
  sv_niva:        { length: 3.720, width: 1.680, height: 1.640, clearance: 0.220, wheelbase: 2.200, frontTrack: 1.430, rearTrack: 1.400, wheelRadius: 0.343, tyreWidth: 0.175 },
  sv_niva_long:   { length: 4.240, width: 1.680, height: 1.640, clearance: 0.220, wheelbase: 2.700, frontTrack: 1.440, rearTrack: 1.420, wheelRadius: 0.343, tyreWidth: 0.175 },
  sa_azlk2141:   { length: 4.350, width: 1.690, height: 1.400, clearance: 0.140, wheelbase: 2.580, frontTrack: 1.440, rearTrack: 1.420, wheelRadius: 0.310, tyreWidth: 0.165 },
  sa_vaz2109:   { length: 4.006, width: 1.650, height: 1.402, clearance: 0.160, wheelbase: 2.460, frontTrack: 1.400, rearTrack: 1.370, wheelRadius: 0.281, tyreWidth: 0.165 },
  sa_oka:         { length: 3.200, width: 1.420, height: 1.400, clearance: 0.150, wheelbase: 2.180, frontTrack: 1.214, rearTrack: 1.204, wheelRadius: 0.260, tyreWidth: 0.135 },
  sa_uaz330364:   { length: 4.535, width: 1.974, height: 2.355, clearance: 0.205, wheelbase: 2.550, frontTrack: 1.445, rearTrack: 1.445, wheelRadius: 0.372, tyreWidth: 0.225, frontOverhang: 1.054 },
  sa_izh2715:     { length: 4.130, width: 1.590, height: 1.825, clearance: 0.185, wheelbase: 2.400, frontTrack: 1.270, rearTrack: 1.270, wheelRadius: 0.305, tyreWidth: 0.175 },
  gt_vaz2110:     { length: 4.265, width: 1.680, height: 1.420, clearance: 0.170, wheelbase: 2.492, frontTrack: 1.410, rearTrack: 1.380, wheelRadius: 0.288, tyreWidth: 0.175 },
  // UAZ manual RE 05808600.072-2000, Fig. 1.9 (the factory hard top, 31514 column): 4025
  // long over the spare on the tailgate, 2020 high; 220 under the single-reduction axles.
  // 215/90-15C cross-ply: 388 free, 364 static, 0.372 rolling.
  cf_uaz31512:    { length: 4.025, width: 1.785, height: 2.020, clearance: 0.220, wheelbase: 2.380, frontTrack: 1.445, rearTrack: 1.445, wheelRadius: 0.372, tyreWidth: 0.215 },
};

function factoryGeometry(id: string): FactoryGeometry {
  const geometry = FACTORY_GEOMETRY[id];
  if (!geometry) throw new Error(`Model "${id}" is missing factory geometry`);
  return geometry;
}



/**
 * Low Poly Soviet Car Pack — fifteen bodies, one FBX each, and the only pack in
 * the catalogue that is about the same cars this game is already about.
 *
 * They needed no conversion and no simplification. Every one is 4.0k-5.8k
 * triangles, nose-first down +Z, with four consistently named wheel meshes.
 * FBXLoader reports the source geometry in centimetres.
 *
 * Colour is UV, not material: each body's UVs point into a region of the pack's
 * shared `albedo.png` palette. The atlas is not one paint picture: it is eighteen
 * solid swatches carrying paint, glass, chrome, lamp and trim colours. The renderer
 * replaces only each body's paint swatch, leaving every functional colour intact.
 *
 * ---- life-size, per body ----
 *
 * The pack is not uniformly scaled. Each source keeps its wheelbase-derived base
 * scale, then render/carmodel.ts fits body width, body-only height and length to
 * FACTORY_GEOMETRY. Axle positions, front/rear tracks and rolling radii are corrected
 * independently, so fixing an over-wide Volga never widens its tyres and fitting a
 * narrow Zhiguli never changes its wheelbase. The corrected body bounds remain the
 * collider bounds; visual and physical proportions therefore cannot diverge.
 *
 * ---- everything else is the real car's ----
 *
 * Engines, gearboxes and final drives are the factory's, from the pack's own Soviet
 * driveline table (parts/registry.ts). Masses are catalogue kerb masses, weight
 * distribution is the factory axle split, steering lock is derived from the published
 * turning circle at each body's own measured wheelbase, and the grip ladder is what
 * period tyres actually pull (see the note above the table).
 *
 * `dragArea` is calibrated, in this order and never before the others: real mass,
 * ratios and driveline efficiency, then the engine's factory curve, then Cd·A as the
 * one number that puts the car on its catalogue top speed at the tools/reality.ts
 * test load. Where AvtoVAZ published a wind-tunnel Cd the result is checked against
 * it and agrees (Samaras); elsewhere no factory Cd or frontal area exists, and one
 * value per BODY SHELL is fitted to its family's top speeds together (2101/2103/2106,
 * 2105/2107, 2102/2104), so a shared shell cannot hide a different engine's error.
 */
interface SovietSpec {
  readonly id: string;
  readonly label: string;
  readonly file: string;
  /** Model-units-to-metres, set from the real car's wheelbase. See the note above. */
  readonly scale: number;
  /** Kerb mass, kg, as delivered. */
  readonly mass: number;
  readonly engineId: string;
  readonly gearboxId: string;
  readonly tankLitres: number;
  readonly wheelGrip: number;
  readonly brakeDecelG: number;
  readonly steerLock: number;
  readonly rearDriveBias: number;
  readonly handlingProfile?: HandlingProfile;
  /** Factory front-axle share of the kerb mass. */
  readonly frontWeightShare: number;
  /** Drag area, Cd·A in m²: see the note above on how it is calibrated. */
  readonly dragArea: number;
  readonly aero: AeroSpec;
  readonly suspension: SuspensionTuning;
  /** The factory tyre (see `TyreSpec`). */
  readonly tyre: TyreSpec;
  readonly storageCells?: number;
}


/*
 * ---- the grip ladder, and why it sits so far below 1.0 ----
 *
 * `wheelGrip` multiplies the surface's one coefficient for drive, braking and
 * cornering alike, so it is the tyre — and these are period Soviet tyres. What the
 * real cars pull on dry asphalt, and what each figure below is calibrated to:
 *
 *   GAZ-21, 6.70-15 cross-ply          0.62 g   a tall, soft, hot-running carcass
 *   GAZ-24, 7.35-14                    0.66 g
 *   Zhiguli, 155/165-80R13 radial      0.70 g   Fiat-era radials, narrow
 *   later classics, 165/80R13          0.72 g
 *   Samara, 165/70R13                  0.78 g   a lower profile and a wider rim
 *   Niva, 175/80R16 all-terrain        0.66 g   soft block tread, tall sidewall
 *   rally 2105                         0.85 g   the only one built to corner
 *
 * The old ladder ran 0.88-1.04, which measured 0.89-1.04 g on the bench: a 1956
 * Volga cornering like a modern hatchback. The stopping distance on dry asphalt IS set
 * here now: every car's brakes (`brakeDecelG`) out-pull its tyres, so a hard stop ends
 * at this tyre's peak and a floored pedal at its sliding plateau. What it used to be —
 * the brakes capped below the tyres to hit a distance — never let a pedal lock a wheel.
 *
 * The ORDER is unchanged and it still runs backwards from every other pack: these
 * are the oldest cars in the catalogue, and the Samaras are the only ones with a
 * decade of tyre development behind them.
 *
 * ---- steering lock ----
 *
 * Every `steerLock` is derived, not chosen. It is the RACK's angle — the bicycle-model
 * angle of the axle's centreline, which the Ackermann geometry shares out as more on
 * the inner wheel and less on the outer (`SuspensionTuning.ackermann`). A factory
 * turning radius is swept by the OUTER FRONT WHEEL, a wheelbase ahead of a turn centre
 * that sits on the rear axle's line, so the turn centre lies `sqrt(turn² − L²) − t/2`
 * to the side of the car, and the lock that puts it there is `atan(L / R) + steerPlay`
 * (the play is subtracted from the rack command before it reaches the tyre). At the
 * 10 km/h tools/reality.ts takes the circle at, the tyres still run a little slip, more
 * on a front-driven or soft-tyred car, so each lock is the one that puts reality.ts on
 * the factory figure: 0.01-0.04 rad over the pure geometry.
 */
/**
 * Floored-pedal brake hardware, g (see `CarModelDef.brakeDecelG`). Both are above
 * every tyre in the catalogue, so a floored pedal locks; they differ only in where on
 * the pedal the lock begins.
 *
 * UNASSISTED: the leg alone on the master cylinder — drums all round on the GAZ-21
 * (igorkalinin.com/volga/data.ru.html), discs and drums with no vacuum servo on the
 * VAZ-2101 and its 2102 estate (the 2101's manifold has no servo take-off; the 2103 was
 * the first with one: gogermetik.com/ustanovka-vakuumnogo-usilitelja-tormozov-na-vaz.html).
 * SERVO: a vacuum (or the GAZ-24's hydro-vacuum) servo, every later car. The Oka's
 * and the IZh-2715-01's servo is not confirmed by a source read here; for them the
 * figure is an assumption, and it moves only the pedal position at which they lock.
 * RALLY: competition pads and linings on the servo car.
 */
const BRAKES_UNASSISTED_G = 1.0;
const BRAKES_SERVO_G = 1.2;
const BRAKES_RALLY_G = 1.4;

const SOVIET_SPECS: readonly SovietSpec[] = [
  {
    // GAZ-21 Volga: 2.445 litre, 70 hp at 4000, three speeds on the column, and
    // 1.46 tonnes of chrome on cross-plies. Turning radius 6.3 m, top speed 130.
    // Cd·A 1.12 from that top speed; no factory Cd exists.
    // Nothing about this car is quick, and its 0.48 rearward weight bias plus a
    // 0.95 Hz front end is why it heaves onto its outside front tyre and stays
    // there.
    // PASSPORT: 130 km/h (autoopt.ru/auto/encyclopedia/car/gaz/mark/gaz-21). No factory
    // 0-100 for the 70 hp car: wiki.zr.ru/ГАЗ-21 prints 34 s for the 65 hp first series.
    // No factory brake figure: igorkalinin.com/volga/data.ru.html leaves the row empty.
    id: 'sv_gaz21',
    label: 'GAZ-21 Volga',
    file: 'gz21.fbx',
    scale: 0.010305,
    mass: 1460,
    // 6.70-15 cross-ply.
    tyre: { construction: 'crossply', aspect: 0.95 },
    engineId: 'engine_zmz_21',
    gearboxId: 'gearbox_gaz_3',
    tankLitres: 60,
    wheelGrip: 0.522,
    brakeDecelG: BRAKES_UNASSISTED_G,
    steerLock: 0.519,
    rearDriveBias: 1,
    frontWeightShare: 0.48,
    dragArea: 1.12,
    aero: AERO_VOLGA_21,
    suspension: SUSP_VOLGA_21,
  },
  {
    // GAZ-24 Volga: the same idea fifteen years later. 95 hp, four speeds on the
    // floor, 145 km/h, and a 5.5 m turning radius on a longer wheelbase (GAZ-24
    // manual) — so it needs MORE lock than the 21 to match it. Cd·A 1.37 from the
    // factory 145 km/h, i.e. Cd ~0.65 on ~2.1 m²: well above ru.wikipedia's unsourced
    // 0.45, which is what 95 hp would need to be a gross rather than a net figure to
    // explain. The catalogue power is used as printed; the drag area carries it.
    // PASSPORT: 145 km/h (igorkalinin.com/volga/data.ru.html). No factory 0-100 for the
    // 95 hp car; secondary sources print 19-22 s (wroom.ru/cars/gaz/24/spec/1: 22 s).
    // Brake: 43.2 m from 80 km/h, for the GAZ-24-10 (autoopt.ru, gaz-24-10).
    id: 'sv_gaz24',
    label: 'GAZ-24 Volga',
    file: 'gz24.fbx',
    scale: 0.009556,
    mass: 1420,
    // 7.35-14 cross-ply.
    tyre: { construction: 'crossply', aspect: 0.95 },
    engineId: 'engine_zmz_24',
    gearboxId: 'gearbox_gaz_4',
    tankLitres: 55,
    wheelGrip: 0.6,
    brakeDecelG: BRAKES_SERVO_G,
    steerLock: 0.638,
    rearDriveBias: 1,
    frontWeightShare: 0.49,
    dragArea: 1.37,
    aero: AERO_VOLGA_24,
    suspension: SUSP_VOLGA_24,
  },
  {
    // VAZ-2101, the Zhiguli. 1.198 litre, 64 hp, 955 kg, 142 km/h in a direct
    // fourth on a 4.30 axle, 0-100 in 20 s (1982 catalogue). The default car, and
    // the one everything else in this table is judged against. Cd·A 0.95 is the
    // 2101/2103/2106 shell's, fitted to the three cars' top speeds together.
    // PASSPORT (driver + passenger): 0-100 20 s, 142 km/h; 43.2 m from 80 km/h at gross
    // mass, 1355 kg (autoprospect.ru/vaz/2101-zhiguli/1-4-tekhnicheskaya-kharakteristika-avtomobilejj.html).
    id: 'sv_vaz2101',
    label: 'VAZ-2101 Zhiguli',
    file: 'vz01.fbx',
    scale: 0.010585,
    mass: 955,
    // 155 R13, the Zhiguli's Fiat-era radial.
    tyre: { construction: 'radial', aspect: 0.8 },
    engineId: 'engine_lada_1200',
    gearboxId: 'gearbox_lada_4',
    tankLitres: 39,
    wheelGrip: 0.558,
    brakeDecelG: BRAKES_UNASSISTED_G,
    steerLock: 0.529,
    rearDriveBias: 1,
    frontWeightShare: 0.51,
    dragArea: 0.95,
    aero: AERO_ZHIGULI,
    suspension: SUSP_ZHIGULI,
  },
  {
    // VAZ-2102: the 2101 as an estate. Same engine on a shorter 4.44 axle, 430 kg
    // of payload rating in the back, and the empty-estate rear end that comes with
    // it. Cd·A 1.07 is the estate shell's, shared with the 2104.
    // PASSPORT (driver + passenger): 0-100 23 s, 137 km/h; 43.2 m from 80 km/h at gross
    // mass (autoprospect.ru/vaz/2101-zhiguli/1-4-tekhnicheskaya-kharakteristika-avtomobilejj.html).
    id: 'sv_vaz2102',
    label: 'VAZ-2102 estate',
    file: 'vz02.fbx',
    scale: 0.010632,
    mass: 1010,
    // 165 R13.
    tyre: { construction: 'radial', aspect: 0.8 },
    engineId: 'engine_lada_1200',
    gearboxId: 'gearbox_lada_4_2102',
    tankLitres: 39,
    wheelGrip: 0.551,
    brakeDecelG: BRAKES_UNASSISTED_G,
    steerLock: 0.531,
    rearDriveBias: 1,
    frontWeightShare: 0.5,
    dragArea: 1.07,
    aero: AERO_ZHIGULI_ESTATE,
    suspension: SUSP_ZHIGULI_ESTATE,
    storageCells: 5,
  },
  {
    // VAZ-2103: 1.452 litre, 71 hp, twin headlights, a tachometer and the 4.10 axle
    // behind the close-ratio box. The fastest of the early saloons at 152 km/h.
    // PASSPORT: 0-100 17 s, 152 km/h; 43.2 m from 80 km/h fully laden
    // (autoopt.ru/auto/encyclopedia/car/vaz/mark/vaz-2103).
    id: 'sv_vaz2103',
    label: 'VAZ-2103',
    file: 'vz03.fbx',
    scale: 0.010632,
    mass: 1030,
    // 165/80 R13.
    tyre: { construction: 'radial', aspect: 0.8 },
    engineId: 'engine_lada_1500',
    gearboxId: 'gearbox_lada_4_tall',
    tankLitres: 39,
    wheelGrip: 0.574,
    brakeDecelG: BRAKES_SERVO_G,
    steerLock: 0.53,
    rearDriveBias: 1,
    frontWeightShare: 0.51,
    dragArea: 0.95,
    aero: AERO_ZHIGULI,
    suspension: SUSP_ZHIGULI,
  },
  {
    // VAZ-2104: the 2105's estate, in its base form with the 2105's 1.3 and 4.3
    // axle (autoopt.ru: 1020 kg, 137 km/h, 18.5 s). The workhorse of the line.
    // PASSPORT: 0-100 18.5 s, 137 km/h (autoopt.ru, vaz-2104); 38 m from 80 km/h laden
    // by its reference to the 2105. Autoreview's 100-0 of 49.4 m is known only second-hand
    // (forum.ixbt.com/post.cgi?id=print%3A70%3A872).
    id: 'sv_vaz2104',
    label: 'VAZ-2104 estate',
    file: 'vz04.fbx',
    scale: 0.010585,
    mass: 1020,
    // 165/80 R13.
    tyre: { construction: 'radial', aspect: 0.8 },
    engineId: 'engine_lada_1300',
    gearboxId: 'gearbox_lada_4_2105',
    tankLitres: 39,
    wheelGrip: 0.56,
    brakeDecelG: BRAKES_SERVO_G,
    steerLock: 0.53,
    rearDriveBias: 1,
    frontWeightShare: 0.5,
    dragArea: 1.07,
    aero: AERO_ZHIGULI_ESTATE,
    suspension: SUSP_ZHIGULI_ESTATE,
    storageCells: 5,
  },
  {
    // VAZ-2105: square lights, the belt-cam 1.3, 47 kW, the close-ratio box on a
    // 4.3 axle. The one everyone's uncle had, and mechanically the plainest car here.
    // Cd·A 0.92 is the 2105/2107 shell's.
    // PASSPORT: 0-100 18 s, 145 km/h; 38 m from 80 km/h (autoopt.ru, vaz-2105).
    id: 'sv_vaz2105',
    label: 'VAZ-2105',
    file: 'vz05.fbx',
    scale: 0.010632,
    mass: 995,
    // 165/80 R13.
    tyre: { construction: 'radial', aspect: 0.8 },
    engineId: 'engine_lada_1300',
    gearboxId: 'gearbox_lada_4_2105',
    tankLitres: 39,
    wheelGrip: 0.57,
    brakeDecelG: BRAKES_SERVO_G,
    steerLock: 0.53,
    rearDriveBias: 1,
    frontWeightShare: 0.51,
    dragArea: 0.92,
    aero: AERO_ZHIGULI,
    suspension: SUSP_ZHIGULI,
  },
  {
    // The pack's rally 2105: stripes, spot lamps, twin Webers, a 6800 rpm limit and
    // 5 cm of extra stance, because a rally car is RAISED. Its 1.6 has nothing
    // below 3000 rpm and everything above it; the springs are the stiffest in the
    // pack and it is the only Soviet body on the sport steering profile, because
    // somebody rebuilt this one to be driven hard.
    // NO PASSPORT: a private build. The works VFTS (160 hp, 8.4 s, 190 km/h:
    // zr.ru/content/articles/933434-dvesti-ne-predel-10-samykh-bys/) is a different
    // engine; this one is held to its own 100 ps engine and the 2107 box: 11 s, 170 km/h,
    // and its stops are its tyres'.
    id: 'sv_vaz2105r',
    label: 'VAZ-2105 rally',
    file: 'vz05r.fbx',
    scale: 0.010632,
    mass: 960,
    // 185-section competition tyre on a 13-inch rim, about a 70 profile.
    tyre: { construction: 'radial', aspect: 0.7 },
    engineId: 'engine_lada_rally',
    gearboxId: 'gearbox_lada_5',
    tankLitres: 39,
    wheelGrip: 0.615,
    // Rally brakes: competition pads and linings on the 2105's servo.
    brakeDecelG: BRAKES_RALLY_G,
    steerLock: 0.526,
    rearDriveBias: 1,
    handlingProfile: 'sport',
    frontWeightShare: 0.52,
    dragArea: 0.9,
    aero: AERO_ZHIGULI,
    suspension: SUSP_LADA_RALLY,
    storageCells: 1,
  },
  {
    // VAZ-2106: 1.569 litre, 75 hp, and the 3.90 axle. 152 km/h, and the strongest
    // pull of the classic saloons.
    // PASSPORT (driver + passenger): 0-100 16 s, 152 km/h; 43.2 m from 80 km/h fully
    // laden (welove2106.narod.ru/objie/ob_1.htm; autoopt.ru prints 38 m).
    id: 'sv_vaz2106',
    label: 'VAZ-2106',
    file: 'vz06.fbx',
    scale: 0.010585,
    mass: 1035,
    // 165/80 R13.
    tyre: { construction: 'radial', aspect: 0.8 },
    engineId: 'engine_lada_1600',
    gearboxId: 'gearbox_lada_4_1600',
    tankLitres: 39,
    wheelGrip: 0.58,
    brakeDecelG: BRAKES_SERVO_G,
    steerLock: 0.53,
    rearDriveBias: 1,
    frontWeightShare: 0.51,
    dragArea: 0.95,
    aero: AERO_ZHIGULI,
    suspension: SUSP_ZHIGULI,
  },
  {
    // VAZ-2107: the 2105 with a grille that thinks it is a Mercedes, the 1.5 and
    // the five-speed. Fifth is an 0.82 overdrive, so it is the relaxed one.
    // PASSPORT (driver + passenger): 0-100 17 s, 150 km/h; 38 m from 80 km/h at the
    // greatest load (vazbook.ru/07/2107/main/manual/osnovnye-ekspluatacionnye-parametry-i-razmery).
    id: 'sv_vaz2107',
    label: 'VAZ-2107',
    file: 'vz07.fbx',
    scale: 0.010632,
    mass: 1030,
    // 165/80 R13.
    tyre: { construction: 'radial', aspect: 0.8 },
    engineId: 'engine_lada_1500',
    gearboxId: 'gearbox_lada_5',
    tankLitres: 39,
    wheelGrip: 0.582,
    brakeDecelG: BRAKES_SERVO_G,
    steerLock: 0.53,
    rearDriveBias: 1,
    frontWeightShare: 0.51,
    dragArea: 0.92,
    aero: AERO_ZHIGULI,
    suspension: SUSP_ZHIGULI,
  },
  {
    // VAZ-2108 Sputnik: the break with everything above it. Front-wheel drive on a
    // transaxle, five speeds, MacPherson struts, rack-and-pinion steering, 900 kg
    // and 62% of it over the front axle. It steers like a different decade because
    // it is one, so it is the first Soviet body on the `road` profile. Cd·A 0.88 from
    // its 148 km/h, which is AvtoVAZ's own wind-tunnel Cd of 0.47 on 1.87 m².
    // PASSPORT (driver + passenger): 0-100 16 s, 148 km/h; 38 m from 80 km/h at gross mass
    // (wiki.zr.ru/Технические_характеристики_автомобилей2108).
    id: 'sv_vaz2108',
    label: 'VAZ-2108 Sputnik',
    file: 'vz08.fbx',
    scale: 0.010123,
    mass: 900,
    // 165/70 R13.
    tyre: { construction: 'radial', aspect: 0.7 },
    engineId: 'engine_samara_1300',
    gearboxId: 'gearbox_samara_5',
    tankLitres: 43,
    wheelGrip: 0.65,
    brakeDecelG: BRAKES_SERVO_G,
    steerLock: 0.59,
    rearDriveBias: 0,
    handlingProfile: 'road',
    frontWeightShare: 0.62,
    dragArea: 0.88,
    aero: AERO_SAMARA_HATCH,
    suspension: SUSP_SAMARA,
    storageCells: 2,
  },
  {
    // VAZ-2109: the five-door Samara. Same running gear, 20 kg and a longer roof.
    // PASSPORT: as the 2108 (wiki.zr.ru); Autoreview's 100-0 of 44.7 m is known only
    // second-hand (forum.ixbt.com/post.cgi?id=print%3A70%3A872).
    id: 'sv_vaz2109',
    label: 'VAZ-2109 Samara',
    file: 'vz09.fbx',
    scale: 0.010123,
    mass: 915,
    // 165/70 R13.
    tyre: { construction: 'radial', aspect: 0.7 },
    engineId: 'engine_samara_1300',
    gearboxId: 'gearbox_samara_5',
    tankLitres: 43,
    wheelGrip: 0.65,
    brakeDecelG: BRAKES_SERVO_G,
    steerLock: 0.59,
    rearDriveBias: 0,
    handlingProfile: 'road',
    frontWeightShare: 0.615,
    dragArea: 0.88,
    aero: AERO_SAMARA_HATCH,
    suspension: SUSP_SAMARA,
    storageCells: 3,
  },
  {
    // VAZ-21099: the Samara with a boot grafted on, the 1.5, and the manual's 3.9-
    // class axle (it lists 3.7 or 3.9). 154 km/h makes it the fastest thing in the
    // pack that was sold as one. Cd·A 0.84: AvtoVAZ's Cd 0.45 on 1.87 m².
    // PASSPORT (driver + passenger): 0-100 13.5 s, 154 km/h; 38 m from 80 km/h at gross
    // mass (wiki.zr.ru/Технические_характеристики_автомобилей2108).
    id: 'sv_vaz21099',
    label: 'VAZ-21099',
    file: 'vz099.fbx',
    scale: 0.010082,
    mass: 970,
    // 165/70 R13.
    tyre: { construction: 'radial', aspect: 0.7 },
    engineId: 'engine_samara_1500',
    gearboxId: 'gearbox_samara_5',
    tankLitres: 43,
    wheelGrip: 0.65,
    brakeDecelG: BRAKES_SERVO_G,
    steerLock: 0.589,
    rearDriveBias: 0,
    handlingProfile: 'road',
    frontWeightShare: 0.6,
    dragArea: 0.84,
    aero: AERO_SAMARA_SALOON,
    suspension: SUSP_SAMARA,
  },
  {
    // VAZ-2121 Niva: 1.6, 73 hp, permanent four-wheel drive through a locking centre
    // diff, 220 mm of clearance and a 2.20 m wheelbase — the shortest in the pack.
    // Its transfer case's high range is folded into the 4.92 final drive, so it is
    // geared a fifth shorter than the 2106 it shares a block with: 132 km/h flat
    // out, and it will pull away from anything here on a surface. Cd·A 1.30 from that
    // 132, Cd 0.536 (ru.wikipedia) on about 2.4 m²; the 2131 shares the nose.
    // PASSPORT (driver + passenger): 0-100 23 s, 132 km/h
    // (lada-niva.ru/niva/soobschenie-s-harakteristikami.html); 40 m from 80 km/h at gross
    // mass (niva-faq.msk.ru/tehnika/obsch/tehdann/213_312.htm).
    id: 'sv_niva',
    label: 'VAZ-2121 Niva',
    file: 'vz21.fbx',
    scale: 0.009649,
    mass: 1150,
    // 175/80 R16.
    tyre: { construction: 'radial', aspect: 0.8 },
    engineId: 'engine_niva_1600',
    gearboxId: 'gearbox_niva_4',
    tankLitres: 42,
    wheelGrip: 0.576,
    brakeDecelG: BRAKES_SERVO_G,
    steerLock: 0.499,
    rearDriveBias: 0.5,
    handlingProfile: 'utility',
    frontWeightShare: 0.53,
    dragArea: 1.3,
    aero: AERO_NIVA,
    suspension: SUSP_NIVA,
    storageCells: 4,
  },
  {
    // PASSPORT: 0-100 25 s, 132 km/h; 40 m from 80 km/h at gross mass, the family's
    // figure (niva-faq.msk.ru/tehnika/obsch/tehdann/213_312.htm).
    id: 'sv_niva_long',
    label: 'VAZ-2131 Niva',
    file: 'vz31.fbx',
    scale: 0.009783,
    mass: 1350,
    // 175/80 R16.
    tyre: { construction: 'radial', aspect: 0.8 },
    engineId: 'engine_niva_1700',
    gearboxId: 'gearbox_niva_5',
    tankLitres: 42,
    wheelGrip: 0.574,
    brakeDecelG: BRAKES_SERVO_G,
    steerLock: 0.522,
    rearDriveBias: 0.5,
    handlingProfile: 'utility',
    frontWeightShare: 0.52,
    dragArea: 1.3,
    aero: AERO_NIVA,
    suspension: SUSP_NIVA,
    storageCells: 6,
  },
];

/**
 * Body-paint swatch used by each Soviet FBX. The shared atlas also carries glass,
 * chrome, lamps, tyres and trim colours; replacing the whole texture would tint
 * those parts too. Recolouring only this UV cell preserves the rest of the authored
 * palette and the rally car's decals.
 */
const SOVIET_PAINT_CELLS: Readonly<Record<string, readonly [number, number]>> = {
  'gz21.fbx': [8, 1],
  'gz24.fbx': [1, 0],
  'vz01.fbx': [0, 0],
  'vz02.fbx': [7, 0],
  // Measured, not authored: this body's coachwork samples (4, 0), and the (0, 1)
  // this used to name is the grey trim swatch — so recolouring it repainted the
  // bumpers and left the car its factory dark blue.
  'vz03.fbx': [4, 0],
  'vz04.fbx': [8, 1],
  'vz05.fbx': [1, 0],
  'vz05r.fbx': [7, 0],
  'vz06.fbx': [0, 0],
  'vz07.fbx': [2, 0],
  'vz08.fbx': [8, 1],
  'vz09.fbx': [4, 0],
  'vz099.fbx': [6, 0],
  'vz21.fbx': [7, 0],
  'vz31.fbx': [0, 0],
};

function sovietLights(file: string): VehicleLightsDef {
  const stem = file.slice(0, -4);
  const prefix = stem.startsWith('gz') ? `g${stem.slice(2)}` : stem.slice(2);
  const headlights = [prefix === '31' ? '31bodyhead;ights' : `${prefix}bodyheadlights`];
  const taillights = [`${prefix}bodytaillights`];
  const reverseLights = ['01', '02', '03'].includes(prefix)
    ? undefined
    : [`${prefix}bodyreverselights`];
  if (prefix === 'g21') return { headlights, taillights, reverseLights };
  if (prefix === 'g24') {
    return {
      headlights,
      taillights,
      reverseLights,
      leftBlinkers: ['g24bodyfrontleftblinker', 'g24bodyrearleftblinker'],
      rightBlinkers: ['g24bodyfrontrightblinker', 'g24bodyrearrightblinker'],
    };
  }
  return {
    headlights,
    taillights,
    reverseLights,
    leftBlinkers: [`${prefix}bodyleftblinkers`],
    rightBlinkers: [`${prefix}bodyrightblinkers`],
  };
}

/**
 * The UAZs' pool: the Nivas' off-road sets, scaled to each UAZ's own tyre (`cloneWheels`).
 * The SAAS UAZ-330364's own wheel is 18-20 segments to the circle and reads as a
 * polygon beside the Soviet pack's 30-32 (owner, 2026-10-11); a borrowed set is also one
 * model fewer to load.
 */
const OFFROAD_WHEEL_SET_POOL = ['sv_niva', 'sv_niva_long'];
/** Shared pool: road Soviet sets only, excluding rally and both Niva sets. */
const SOVIET_WHEEL_SET_POOL = [
  'sv_gaz21',
  'sv_gaz24',
  'sv_vaz2101',
  'sv_vaz2102',
  'sv_vaz2103',
  'sv_vaz2104',
  'sv_vaz2105',
  'sv_vaz2106',
  'sv_vaz2107',
  'sv_vaz2108',
  'sv_vaz2109',
  'sv_vaz21099',
] as const;

function sovietWheelNodes(file: string): WheelNodeNames {
  const stem = file.slice(0, -4);
  const prefix = stem.startsWith('gz') ? `g${stem.slice(2)}` : stem.slice(2);
  return {
    wheel_fl: [`${prefix}wheel_fl`],
    wheel_fr: [`${prefix}wheel_fr`],
    wheel_rl: [`${prefix}wheel_bl`],
    wheel_rr: [`${prefix}wheel_br`],
  };
}

function sharedSovietWheelPool(file: string): readonly string[] | undefined {
  if (['vz05r.fbx', 'vz21.fbx', 'vz31.fbx'].includes(file)) return undefined;
  return SOVIET_WHEEL_SET_POOL;
}


/** One entry per body; the pack's scale, palette and wheel detection are shared. */
const SOVIET_CARS: readonly Entry[] = SOVIET_SPECS.map((spec) => ({
  id: spec.id,
  label: spec.label,
  dir: SOVIET,
  glb: spec.file,
  textureFile: `${SOVIET}/albedo.png`,
  // Every body in this pack draws its windows as a region of the one body mesh,
  // UV-mapped to the atlas's dark teal swatch. Measured on all fifteen.
  glassUvCell: [3, 1],
  lights: sovietLights(spec.file),
  // Soviet FBX wheel names are stable; explicit nodes also keep headless and
  // browser loaders on the same four-corner interpretation.
  detectWheels: false,
  wheelNodes: sovietWheelNodes(spec.file),
  wheelSetPool: sharedSovietWheelPool(spec.file),
  bodyClass: 'car',
  storageCells: spec.storageCells,
  mass: spec.mass,
  engineId: spec.engineId,
  gearboxId: spec.gearboxId,
  tankLitres: spec.tankLitres,
  wheelGrip: spec.wheelGrip,
  brakeDecelG: spec.brakeDecelG,
  // FBXLoader reports this pack in centimetres, and each body's factor makes that
  // body life-size against the real car's wheelbase (see the pack note above).
  scale: spec.scale,
  suspension: spec.suspension,
  steerLock: spec.steerLock,
  rearDriveBias: spec.rearDriveBias,
  handlingProfile: spec.handlingProfile,
  frontWeightShare: spec.frontWeightShare,
  dragArea: spec.dragArea,
  aero: spec.aero,
  tyre: spec.tyre,
}));

/**
 * Texture-free GTA SA conversions. Scale is fitted from each DFF dummy axle
 * spacing to the real wheelbase; the runtime never sees source pack naming.
 */
const SAAS_SPECS: readonly Entry[] = [
  {
    // AZLK-2141-01 as the 1998 catalogue lists it (autoopt.ru): the VAZ-2106-70 1.6,
    // the 2141 five-speed on a 3.9 axle, 1055 kg, 158 km/h, 0-100 in 14.9 s and a
    // 5.0 m turning radius. Cd·A 0.86 from that 158: the period literature's Cd of
    // 0.35-0.38 on 1.89 m² would give 172 km/h from this engine, so either figure
    // is optimistic and the top speed, the one the catalogue stands behind, wins.
    // PASSPORT (2141-01): 0-100 14.9 s, 158 km/h (autoopt.ru, moskvich-2141; the repair
    // manual says at most 15.5 s and 155 km/h); 43.2 m from 80 km/h laden. THIS IS NOT THE
    // SVYATOGOR'S: the 21415 "Svyatogor" had the Renault F3R 2.0, 113 hp, 1090 kg, 0-100
    // 11.5 s, 175 km/h (wiki.zr.ru/Москвич-2141_«Святогор»; alekohistory.narod.ru/m2141tec.htm).
    // The label names the Svyatogor and every figure below is the 2141-01.
    id: 'sa_azlk2141',
    label: 'AZLK-2141 Svyatogor',
    dir: SAAS,
    glb: 'azlk2141.glb',
    bodyClass: 'car',
    scale: 0.86595,
    mass: 1055,
    // 165/80 R13 class road radial.
    tyre: { construction: 'radial', aspect: 0.8 },
    engineId: 'engine_i4_1600',
    gearboxId: 'gearbox_manual5',
    tankLitres: 55,
    wheelGrip: 0.65,
    brakeDecelG: BRAKES_SERVO_G,
    suspension: SUSP_SAMARA,
    steerLock: 0.658,
    rearDriveBias: 0,
    handlingProfile: 'road',
    frontWeightShare: 0.62,
    dragArea: 0.86,
    aero: AERO_AZLK_2141,
    wheelSetPool: SOVIET_WHEEL_SET_POOL,
  },
  {
    // VAZ-2109, 1991, 1.3 L carburettor, five-speed FWD.
    // This personal-use conversion is kept local to the application catalogue.
    // PASSPORT: as the 2108/2109 (wiki.zr.ru/Технические_характеристики_автомобилей2108).
    id: 'sa_vaz2109',
    label: 'VAZ-2109',
    dir: SAAS,
    glb: 'vaz2109.glb',
    bodyClass: 'car',
    scale: 1,
    mass: 915,
    // 165/70 R13.
    tyre: { construction: 'radial', aspect: 0.7 },
    engineId: 'engine_samara_1300',
    gearboxId: 'gearbox_samara_5',
    tankLitres: 43,
    wheelGrip: 0.65,
    brakeDecelG: BRAKES_SERVO_G,
    steerLock: 0.59,
    rearDriveBias: 0,
    handlingProfile: 'road',
    frontWeightShare: 0.62,
    dragArea: 0.88,
    aero: AERO_SAMARA_HATCH,
    suspension: SUSP_SAMARA,
    storageCells: 3,
    paintStyle: 'solid-paint',
    glassMaterial: 'car_glass',
    wheelNodes: {
      wheel_fl: ['wheel_fl'],
      wheel_fr: ['wheel_fr'],
      wheel_rl: ['wheel_rl'],
      wheel_rr: ['wheel_rr'],
    },
    lights: {
      headlights: ['headlights'],
      taillights: ['taillights'],
      brakeLights: ['brake_lights'],
      reverseLights: ['reverse_lights'],
      leftBlinkers: ['front_blinker_left', 'side_blinker_left', 'rear_blinker_left'],
      rightBlinkers: ['front_blinker_right', 'side_blinker_right', 'rear_blinker_right'],
    },
  },
  {
    // VAZ-1111, 1988-1996, per its factory manual: 635 kg kerb, 0.65 litre twin,
    // four-speed transaxle on a 4.54 final drive, 135/80 R12 on 4B-12 rims, 30
    // litre tank, a 4.8 m turning radius by the outer wheel's track, and 120 km/h
    // and 0-100 in 30 s with a driver and one passenger aboard. Cd·A 0.68: Za
    // Rulyom's Cd 0.40 on the textbook's 1.69 m².
    // PASSPORT (driver + passenger): 0-100 30 s, 120 km/h; 38 m from 80 km/h
    // (autoopt.ru/auto/encyclopedia/car/vaz/mark/vaz-1111).
    id: 'sa_oka',
    label: 'VAZ-1111 Oka',
    dir: SAAS,
    glb: 'oka.glb',
    // The pack drew this body's rear screen as a `car_trim` plate filling the tailgate's
    // opening instead of glass, the one window in the fleet that is not `car_glass`:
    // render/carmodel.ts cuts that plate into the glass at load (CarModelDef.rearScreenMaterial).
    rearScreenMaterial: 'car_trim',
    bodyClass: 'car',
    scale: 0.97465,
    mass: 635,
    // 135/80 R12.
    tyre: { construction: 'radial', aspect: 0.8 },
    engineId: 'engine_vaz_1111',
    gearboxId: 'gearbox_oka_4',
    tankLitres: 30,
    wheelGrip: 0.61,
    brakeDecelG: BRAKES_SERVO_G,
    // MacPherson struts in front, trailing arms on an elastic cross-beam behind:
    // the Samara's layout, and its preset.
    suspension: SUSP_SAMARA,
    steerLock: 0.557,
    rearDriveBias: 0,
    handlingProfile: 'road',
    // No factory axle loads are published; transverse front-drive default.
    frontWeightShare: 0.62,
    dragArea: 0.68,
    aero: AERO_OKA,
    lights: {
      // Headlamps carry the position lamps inside them. Amber indicators sit in the
      // bumper and on each front wing. The OSVAR 43.3716 rear lamp stacks a clear
      // reversing block, an amber indicator and red running/stop on one 21/5 W
      // bulb. The red fog lamp in the left of the rear bumper is `rear_passive`:
      // nothing in the game switches it.
      headlights: ['headlights'],
      taillights: ['taillights'],
      reverseLights: ['reverse_lights'],
      leftBlinkers: ['front_blinker_left', 'rear_blinker_left'],
      rightBlinkers: ['front_blinker_right', 'rear_blinker_right'],
    },
    wheelSetPool: SOVIET_WHEEL_SET_POOL,
  },
  {
    // PASSPORT: 110 km/h in the factory manual (РЭ 05808600.104-2006, uaz-business.ru),
    // 105 at truck-and-bus.ru; no 0-100 and no braking row is published.
    id: 'sa_uaz330364',
    label: 'UAZ-330364',
    dir: SAAS,
    glb: 'uaz330364.glb',
    bodyClass: 'truck',
    scale: 0.880927,
    mass: 1845,
    // 225/75 R16.
    tyre: { construction: 'radial', aspect: 0.75 },
    engineId: 'engine_umz_4213',
    gearboxId: 'gearbox_uaz_4',
    tankLitres: 56,
    wheelGrip: 0.59,
    brakeDecelG: BRAKES_SERVO_G,
    // The front is a beam too, on kingpins: its wheels stay square to the road in roll,
    // with the factory +1° of camber, and the axle yaws on its leaves as it rolls.
    suspension: {
      ...SUSP_TRUCK,
      ackermann: 0.8,
      frontCamberDeg: 1,
      frontRollCamber: 0,
      frontRollSteer: 0.06,
    },
    // Beam axles on leaf springs at BOTH ends and no anti-roll bars: the roll centre
    // sits at the spring seats on top of each axle, not at a pickup's front wishbones,
    // and the leaves hang under the frame rails well inboard of the wheels, which takes
    // roll stiffness away rather than adding it (see `SuspensionTuning.frontBar`).
    rollCentre: { front: 0.45, rear: 0.48 },
    antiRoll: { front: -0.25, rear: -0.25 },
    steerLock: 0.487,
    rearDriveBias: 0.5,
    handlingProfile: 'utility',
    // Factory kerb axle loads: 1180 kg front, 665 kg rear. Boxy cab-over body:
    // Cd·A 3.45 from the 330364's 105 km/h (truck-and-bus.ru), 0.74 of the
    // 1.97 m × 2.355 m frontal envelope. No factory Cd exists. Lock puts it on the
    // UAZ-2206's 6.3 m (autoopt.ru, the same chassis).
    frontWeightShare: 1180 / 1845,
    dragArea: 3.45,
    aero: AERO_UAZ_330364,
    // A working 4x4 on off-road wheels: the Nivas' (OFFROAD_WHEEL_SET_POOL).
    wheelSetPool: OFFROAD_WHEEL_SET_POOL,
    loadedRideDrop: 0.037,
    secondaryPaintMaterial: 'car_bed_paint',
    wheelNodes: {
      wheel_fl: ['wheel_fl'],
      wheel_fr: ['wheel_fr'],
      wheel_rl: ['wheel_rl'],
      wheel_rr: ['wheel_rr'],
    },
    lights: {
      // The lower front semicircles are white position lamps and therefore share
      // the headlight control; the upper semicircles are the actual indicators.
      headlights: ['headlights'],
      taillights: ['taillights'],
      reverseLights: ['reverse_lights'],
      leftBlinkers: ['front_blinker_left', 'rear_blinker_left'],
      rightBlinkers: ['front_blinker_right', 'rear_blinker_right'],
    },
  },
  {
    // PASSPORT: 125 km/h (truck-and-bus.ru/brands/izh/izh-2715/). No factory 0-100: 19 s
    // in ru.wikipedia Иж-2715 is unsourced. 43.2 m from 80 km/h is the first-generation
    // 2715's (nashi-avto.ru); none was found for the -01.
    id: 'sa_izh2715',
    label: 'IZH-2715-01',
    dir: SAAS,
    glb: 'izh2715.glb',
    bodyClass: 'truck',
    scale: 0.863496,
    mass: 1015,
    // 1984-1997 2715-01 in its factory low-octane commercial specification:
    // UZAM-412DE, 1478 cc, 49 kW and 102 Nm.
    // 175/80 R13.
    tyre: { construction: 'radial', aspect: 0.8 },
    engineId: 'engine_uzam_412de',
    // Moskvich/IZH four-speed with the 4.22 working-vehicle final drive.
    gearboxId: 'gearbox_izh_4',
    tankLitres: 46,
    // 175/80 R13 period road tyre; same dry-road calibration as the 2104 estate.
    wheelGrip: 0.56,
    brakeDecelG: BRAKES_SERVO_G,
    // Rear leaf springs carrying a 500 kg payload; not the Zhiguli coil-sprung estate.
    suspension: SUSP_TRUCK,
    // Factory outer-front turning radius is 5.25 m (autoopt.ru, IZH-2715); the lock is
    // the one that measures it on tools/reality.ts, like every other.
    steerLock: 0.557,
    rearDriveBias: 1,
    handlingProfile: 'classic',
    // Factory unladen axle loads: 550 kg front, 465 kg rear.
    frontWeightShare: 550 / 1015,
    // No factory Cd is published. CdA 1.42 m² is derived from the factory
    // 125 km/h maximum with this engine, gearing, efficiency and tyre.
    dragArea: 1.42,
    aero: AERO_IZH_2715,
    lights: {
      // Late PF10 front units: amber upper indicators and clear lower position
      // lenses. UP112 triangular rear indicators are independent of the FP112 /
      // IZHFS4 running-stop blocks and their clear reversing sections.
      headlights: [
        'headlights_left_0', 'headlights_left_1', 'headlights_left_2',
        'headlights_left_3', 'headlights_left_4', 'headlights_left_5', 'headlights_left_6',
        'headlights_right_0', 'headlights_right_1', 'headlights_right_2', 'headlights_right_3',
        'front_position_left_0', 'front_position_left_1',
        'front_position_left_2', 'front_position_left_3',
      ],
      taillights: [
        'taillights_left_0', 'taillights_left_1', 'taillights_left_2',
        'taillights_left_3', 'taillights_left_4', 'taillights_left_5', 'taillights_left_6',
        'taillights_right_0', 'taillights_right_1', 'taillights_right_2',
        'taillights_right_3', 'taillights_right_4', 'taillights_right_5', 'taillights_right_6',
      ],
      reverseLights: ['reverse_lights_left_0', 'reverse_lights_right_0'],
      leftBlinkers: [
        'front_blinker_left_0', 'front_blinker_left_1',
        'front_blinker_left_2', 'front_blinker_left_3',
        'rear_blinker_left_0', 'rear_blinker_left_1',
        'rear_blinker_left_2', 'rear_blinker_left_3',
      ],
      rightBlinkers: [
        'front_blinker_right_0', 'front_blinker_right_1',
        'front_blinker_right_2', 'front_blinker_right_3',
        'rear_blinker_right_0', 'rear_blinker_right_1',
        'rear_blinker_right_2', 'rear_blinker_right_3',
      ],
    },
    wheelSetPool: SOVIET_WHEEL_SET_POOL,
  },
];

const SAAS_CARS: readonly Entry[] = SAAS_SPECS.map((spec) => ({
  ...spec,
  glassMaterial: 'car_glass',
  paintStyle: 'solid-paint',
  lights: spec.lights ?? {
    headlights: ['headlights'],
    taillights: ['taillights'],
  },
  wheelNodes: spec.wheelNodes ?? {
    wheel_fl: ['wheel_fl', 'hub_fl'],
    wheel_fr: ['wheel_fr', 'hub_fr'],
    wheel_rl: ['wheel_rl', 'hub_rl'],
    wheel_rr: ['wheel_rr', 'hub_rr'],
  },
}));

/**
 * GTA V add-on conversions. One body so far: the VAZ-2110, extracted from the
 * fragment's skinned body mesh and its single authored wheel.
 *
 * Scale comes from the wheelbase, as everywhere else: the source measures 2.792
 * between axle centres against the real car's 2492 mm, so 0.89255 puts the track
 * on 1.39 m, the body on 4.24 m and the roof on 1.41 m — the factory figures.
 *
 * The 2110 is a Samara underneath: MacPherson struts in front, a trailing-arm
 * torsion beam behind, transverse 1.5 and a five-speed transaxle driving the
 * front wheels, and the 1.5 is the 21083's derivative (the 2110 manual's carburettor
 * rating, 52.0 kW and 103.9 Nm, is within 1% and 2.5% of it). Cd is the one number
 * the car was actually famous for: 0.33-0.334 in AvtoVAZ's tunnel, on 2.04 m² of
 * frontal area, so 0.68 m² of drag area.
 */
const GTAV_SPECS: readonly Entry[] = [
  {
    // PASSPORT (driver + passenger): 0-100 15 s, 162 km/h; 38 m from 80 km/h at gross mass
    // (manual.countryauto.ru/vaz/2110/1-obwie-svedenija.html). Za Rulem measured the
    // VAZ-21102 at 55.0 m from 100 km/h (zr.ru/content/articles/10785-kak_popast_v_desatku/).
    id: 'gt_vaz2110',
    label: 'VAZ-2110',
    dir: GTAV,
    glb: 'vaz2110.glb',
    bodyClass: 'car',
    scale: 0.89255,
    mass: 1010,
    // 175/70 R13.
    tyre: { construction: 'radial', aspect: 0.7 },
    engineId: 'engine_samara_1500',
    gearboxId: 'gearbox_samara_5',
    tankLitres: 43,
    wheelGrip: 0.66,
    brakeDecelG: BRAKES_SERVO_G,
    suspension: SUSP_SAMARA,
    steerLock: 0.604,
    rearDriveBias: 0,
    wheelSetPool: SOVIET_WHEEL_SET_POOL,
    frontWeightShare: 0.62,
    dragArea: 0.68,
    aero: AERO_VAZ_2110,
  },
];

const GTAV_CARS: readonly Entry[] = GTAV_SPECS.map((spec) => ({
  ...spec,
  glassMaterial: 'car_glass',
  paintStyle: 'solid-paint',
  lights: {
    headlights: ['headlights'],
    taillights: ['taillights'],
    brakeLights: ['brake_lights'],
    reverseLights: ['reverse_lights'],
    leftBlinkers: ['front_blinker_left', 'rear_blinker_left'],
    rightBlinkers: ['front_blinker_right', 'rear_blinker_right'],
  },
  // One wheel mesh instanced at four corners: tyre, rim and hub are one node.
  wheelNodes: {
    wheel_fl: ['wheel_fl'],
    wheel_fr: ['wheel_fr'],
    wheel_rl: ['wheel_rl'],
    wheel_rr: ['wheel_rr'],
  },
}));

/**
 * Bodies built by `tools/carforge` from factory drawings, in the Soviet pack's own form
 * (see the pack note at the top): the shared atlas, glass in its (3, 1) cell, paint in
 * (0, 0), lamp and wheel nodes named `<spec id>body<role>` and `<spec id>wheel_<corner>`.
 */
const CARFORGE_CARS: readonly Entry[] = [
  {
    // UAZ-31512, the civilian 469 after 1985, with the factory hard top. Built from the
    // UAZ-3151 drawing (tools/carforge/examples/sheet_uaz3151.json). Everything below is
    // the UAZ manual RE 05808600.072-2000 (2002) unless named: hard-top kerb 1750 kg,
    // 950 front / 800 rear (31514 column, p. 10); UMZ-4178; the all-synchromesh box,
    // 3.78/2.60/1.55/1.00 on the 4.625 axles, which is `gearbox_uaz_4`'s; two 39 L tanks;
    // drums with a vacuum booster; leaf springs at both ends, no anti-roll bar; 6.3 m at
    // the outer front wheel with 27° on the inner one.
    // PASSPORT: 110 km/h (p. 10; the 1993 catalogue says 115). No 0-100. 43.2 m from
    // 80 km/h (autoopt.ru, UAZ-3151 1993 catalogue). No Cd: Cd·A from the top speed.
    id: 'cf_uaz31512',
    label: 'UAZ-31512',
    dir: CARFORGE,
    glb: 'uaz31512.fbx',
    textureFile: `${SOVIET}/albedo.png`,
    paintStyle: 'soviet-atlas',
    paintUvCell: [0, 0],
    glassUvCell: [3, 1],
    detectWheels: false,
    wheelNodes: {
      wheel_fl: ['uaz31512wheel_fl'],
      wheel_fr: ['uaz31512wheel_fr'],
      wheel_rl: ['uaz31512wheel_bl'],
      wheel_rr: ['uaz31512wheel_br'],
    },
    // Off-road wheels from the Nivas, as the UAZ-330364 (OFFROAD_WHEEL_SET_POOL).
    wheelSetPool: OFFROAD_WHEEL_SET_POOL,
    bodyClass: 'car',
    scale: 0.01,
    mass: 1750,
    // 215/90-15C (Я-245-1), cross-ply.
    tyre: { construction: 'crossply', aspect: 0.9 },
    engineId: 'engine_umz_4178',
    gearboxId: 'gearbox_uaz_4',
    tankLitres: 78,
    wheelGrip: 0.55,
    brakeDecelG: BRAKES_SERVO_G,
    // Beam axles on leaves at both ends, as the UAZ-330364's chassis.
    suspension: {
      ...SUSP_TRUCK,
      ackermann: 0.8,
      frontCamberDeg: 1,
      frontRollCamber: 0,
      frontRollSteer: 0.06,
    },
    rollCentre: { front: 0.45, rear: 0.48 },
    antiRoll: { front: -0.25, rear: -0.25 },
    // 0.455 puts the outer front wheel on the manual's 6.3 m circle (tools/reality.ts);
    // the 27° (0.471) it prints for the inner wheel turned it 4% tighter.
    steerLock: 0.455,
    rearDriveBias: 0.5,
    handlingProfile: 'utility',
    frontWeightShare: 950 / 1750,
    // Cd·A 2.2 holds the manual's 110 km/h (tools/reality.ts): Cd 0.8 on the 2.75 m² below.
    dragArea: 2.2,
    aero: AERO_UAZ_3151,
    lights: {
      // The front units under the headlamps: amber indicator over a sidelight, which
      // shares the headlight control. At the rear one unit per corner, amber over a red
      // tail and brake section; one reverse lamp.
      headlights: ['uaz31512bodyheadlights'],
      taillights: ['uaz31512bodytaillights'],
      reverseLights: ['uaz31512bodyreverselights'],
      leftBlinkers: ['uaz31512bodyleftblinkers'],
      rightBlinkers: ['uaz31512bodyrightblinkers'],
    },
  },
];

const ENTRIES: readonly Entry[] = [
  // -------------------------------------------------------------------------
  // Low Poly Soviet Car Pack. Fifteen FBX bodies, one per model, each carrying
  // its own wheels (found by shape) and taking its colour from the pack's shared
  // palette atlas. Life-size in centimetres, nose-first down +Z, 4-6k triangles.
  // -------------------------------------------------------------------------
  ...SOVIET_CARS,

  // -------------------------------------------------------------------------
  // Private GTA SA mod conversions. Their DFF-specific hierarchy and material
  // names are normalized offline into the explicit six-role runtime contract.
  // -------------------------------------------------------------------------
  ...SAAS_CARS,

  // -------------------------------------------------------------------------
  // GTA V add-on fragments. One skinned body mesh and one wheel per .yft, cut
  // to the exterior and meshopt-compressed without geometry decimation.
  // -------------------------------------------------------------------------
  ...GTAV_CARS,

  // -------------------------------------------------------------------------
  // Built here by tools/carforge from factory drawings, in the Soviet pack's form.
  // -------------------------------------------------------------------------
  ...CARFORGE_CARS,
];
export const CAR_MODELS: readonly CarModelDef[] = ENTRIES.map((e) => ({
  id: e.id,
  label: e.label,
  file: `${e.dir}/${e.glb}`,
  fit: modelFit(e.id),
  textureFile: e.textureFile,
  paintStyle: e.paintStyle ?? (e.dir === SOVIET ? 'soviet-atlas' : undefined),
  secondaryPaintMaterial: e.secondaryPaintMaterial,
  paintUvCell: e.paintUvCell ?? (e.dir === SOVIET ? SOVIET_PAINT_CELLS[e.glb] : undefined),
  glassMaterial: e.glassMaterial,
  glassUvCell: e.glassUvCell,
  rearScreenMaterial: e.rearScreenMaterial,
  factory: factoryGeometry(e.id),
  wheelSetPool: e.wheelSetPool,
  loadedRideDrop: e.loadedRideDrop,
  wheelNodes: e.wheelNodes,
  bodyClass: e.bodyClass,
  scale: e.scale ?? 1,
  yaw: e.yaw,
  mass: e.mass,
  engineId: e.engineId,
  gearboxId: e.gearboxId,
  tankLitres: e.tankLitres,
  wheelGrip: e.wheelGrip,
  brakeDecelG: e.brakeDecelG,
  suspension: e.suspension ?? SUSP_CAR,
  steerLock: e.steerLock,
  rearDriveBias: e.rearDriveBias,
  handlingProfile: e.handlingProfile ?? 'classic',
  frontWeightShare: e.frontWeightShare,
  antiRoll: e.antiRoll,
  rollCentre: e.rollCentre,
  tyre: e.tyre,
  frontDiff: e.frontDiff,
  rearDiff: e.rearDiff,
  dragArea: e.dragArea,
  aero: e.aero,
  lights: e.lights,
  storageCells: TRUNK_CELL_COUNT,
}));

const BY_ID = new Map(CAR_MODELS.map((m) => [m.id, m]));

/**
 * The model a new game starts in and every unknown saved id resolves to. The
 * Zhiguli: the cheapest, softest, most ordinary thing in the catalogue, and the
 * one car this game is most about.
 */
export const DEFAULT_CAR_MODEL_ID = 'sv_vaz2101';

export function carModel(id: string): CarModelDef {
  const m = BY_ID.get(id);
  if (!m) throw new Error(`Unknown car model "${id}"`);
  return m;
}

export function hasCarModel(id: string): boolean {
  return BY_ID.has(id);
}

/** The engine spec behind a model, resolved through the part-variant table. */
export function modelEngine(def: CarModelDef): EngineSpec {
  const spec = variant(def.engineId).engine;
  if (!spec) throw new Error(`Car model "${def.id}" names a non-engine variant`);
  return spec;
}

export function modelGearbox(def: CarModelDef): GearboxSpec {
  const spec = variant(def.gearboxId).gearbox;
  if (!spec) throw new Error(`Car model "${def.id}" names a non-gearbox variant`);
  return spec;
}
