// Build the whole look-asset set, or one group of it.
//
//   node tools/look/build.mjs                    # everything (needs the Blender runs)
//   node tools/look/build.mjs --only ground,road # one group; groups: noise ground
//                                                # road grass bush trees
//   node tools/look/build.mjs --manifest         # rewrite manifest.json from metadata only
//
// Each builder module exports:
//   name     group id
//   order    build order (ground before road before grass/trees)
//   sources  [{ id, provider, url, license, usedFor: [...] }]
//   outputs  [{ file, size:[w,h], channels, tiling_m, role, note, ... }]
//   build({ force })  writes the files into public/look
//
// manifest.json and LICENSES.md are generated from those declarations, so a new
// output shows up in both by being declared once.

import { readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { LOOK, OUTDIR, ROOT, flags, hasFlag, ensureDirs } from './lib/util.mjs';

const GROUPS = ['noise', 'ground', 'road', 'grass', 'bush', 'trees'];

function selected() {
  const only = [...flags].find((f) => f.startsWith('--only'));
  if (!only) return GROUPS;
  const list = (only.includes('=') ? only.split('=')[1] : process.argv[process.argv.indexOf(only) + 1]) ?? '';
  return list
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
}

async function loadGroup(id) {
  const file = path.join(LOOK, id + '.mjs');
  try {
    return await import(file);
  } catch (err) {
    if (err.code === 'ERR_MODULE_NOT_FOUND' && err.message.includes(id + '.mjs'))
      throw new Error(`builder tools/look/${id}.mjs is missing`);
    throw err;
  }
}

const bytes = async (file) => {
  try {
    return (await stat(file)).size;
  } catch {
    return 0;
  }
};

async function writeManifest(modules) {
  const files = {};
  let total = 0;
  let missing = 0;
  const order = ['noise', 'ground', 'road', 'grass', 'bush', 'trees'];
  const mods = [...modules].sort((a, b) => order.indexOf(a.name) - order.indexOf(b.name));
  for (const mod of mods) {
    for (const o of mod.outputs ?? []) {
      const size = await bytes(path.join(OUTDIR, o.file));
      if (!size) missing++;
      total += size;
      files[o.file] = { group: mod.name, bytes: size, ...o };
    }
  }
  const manifest = {
    note: 'Generated by tools/look/build.mjs — see tools/look/README.md. Paths are relative to /look/. Sizes are pixels; tiling_m is the world period in metres that one full texture repeat represents. Height channels are 0 = base, 1 = crest. Normal maps are OpenGL tangent-space (+Y up, +Z toward the viewer).',
    totalBytes: total,
    fileCount: Object.keys(files).length,
    missingFiles: missing,
    files
  };
  await writeFile(path.join(OUTDIR, 'manifest.json'), JSON.stringify(manifest, null, 1) + '\n');
  return manifest;
}

async function writeLicenses(modules) {
  const rows = [];
  for (const mod of modules)
    for (const s of mod.sources ?? [])
      rows.push({ group: mod.name, ...s });
  rows.sort((a, b) => (a.provider + a.id).localeCompare(b.provider + b.id));
  const byProvider = {};
  for (const r of rows) (byProvider[r.provider] ??= []).push(r);

  let md = `# Лицензии ассетов /look

Все исходные материалы — **CC0 1.0 Universal** (public domain dedication). Правило
из \`docs/renderer-v2.md\`: только CC0. Ничего из slowroads не копировалось: у него
закрытый исходник, у нас — свои источники, свои рендеры и свои скрипты.

Сборка повторяется командой \`node tools/look/build.mjs\` (см. \`tools/look/README.md\`);
скачанные исходники лежат в \`tools/look/.cache\` (не коммитится), готовые текстуры —
в \`public/look\`.

## Как читать таблицы

- **id** — идентификатор ассета у поставщика;
- **что стало** — файлы в \`public/look\`, в которые он вошёл;
- **URL** — точная ссылка, по которой скрипт скачивает исходник.

`;
  for (const [provider, list] of Object.entries(byProvider)) {
    const title = {
      ambientCG: 'ambientCG (ambientcg.com)',
      'Poly Haven': 'Poly Haven (polyhaven.com)',
      'Blender render': 'Собственные рендеры (Blender 5.2)',
      generated: 'Сгенерировано кодом (our code)'
    }[provider] ?? provider;
    md += `## ${title}\n\n`;
    if (provider === 'generated' || provider === 'Blender render') {
      md += `Лицензия: CC0 1.0 (наши собственные работы).\n\n`;
      md += `| id | что стало | как получено |\n|---|---|---|\n`;
      for (const r of list) md += `| \`${r.id}\` | ${(r.usedFor ?? []).map((f) => '`' + f + '`').join(', ')} | ${r.url} |\n`;
    } else {
      md += `Лицензия: CC0 1.0 Universal. Подтверждение: страница ассета, поле «License».\n\n`;
      md += `| id | что стало | исходник |\n|---|---|---|\n`;
      for (const r of list) md += `| \`${r.id}\` | ${(r.usedFor ?? []).map((f) => '`' + f + '`').join(', ')} | ${r.url} |\n`;
    }
    md += '\n';
  }
  md += `## Обработка

Исходные фотографии не публикуются как есть. Скрипты \`tools/look/*.mjs\` приводят их
к 1024² (или к размеру атласа), убирают крупные низкочастотные пятна (которые при
повторе давали бы узор), выравнивают яркость, переводят в серое там, где цвет даёт
шейдер, и складывают карту высот в альфу. Приёмы — свои; числа приёмов slowroads
(setgound: полоса 7 м, четыре краски, «сияние») взяты из \`docs/slowroads-steam/notes/\`
как ориентир, код не копировался.
`;
  await writeFile(path.join(OUTDIR, 'LICENSES.md'), md);
  return rows.length;
}

async function main() {
  await ensureDirs();
  const only = selected();
  // Every module is loaded for its metadata even when only some are built, so a
  // `--only ground` run never drops the other groups from manifest.json or
  // LICENSES.md.
  const all = await Promise.all(GROUPS.map(loadGroup));
  const modules = all.filter((m) => only.includes(m.name));
  if (hasFlag('manifest')) {
    const m = await writeManifest(all);
    console.log(`manifest.json: ${m.fileCount} files, ${(m.totalBytes / 1048576).toFixed(1)} MiB, ${m.missingFiles} missing`);
    return;
  }
  for (const mod of modules.sort((a, b) => (a.order ?? 99) - (b.order ?? 99))) {
    console.log(`\n=== ${mod.name} ===`);
    const t0 = Date.now();
    await mod.build({ force: hasFlag('force') });
    console.log(`--- ${mod.name} done in ${((Date.now() - t0) / 1000).toFixed(1)} s`);
  }
  const m = await writeManifest(all);
  const n = await writeLicenses(all);
  console.log(
    `\nmanifest.json: ${m.fileCount} files, ${(m.totalBytes / 1048576).toFixed(1)} MiB, ${m.missingFiles} missing; LICENSES.md: ${n} sources`
  );
  const entries = await readdir(OUTDIR);
  console.log(`public/look: ${entries.length} entries`);
}

main().catch((err) => {
  console.error(err.stack || err.message);
  process.exit(1);
});
