import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';

import { imageLoader } from './groundtextures';
import { maxAnisotropy } from '../texturequality';

/**
 * THE TREE ASSETS: the atlases, the models and the layout they are cut in.
 *
 * WHAT IS BEING LOADED. `public/look` holds, per season, one deciduous atlas (four
 * species columns, each with a whole-tree sprite, six crown modules and a bark strip,
 * plus a tangent-space normal map), one conifer atlas (two columns of whorl slices, side
 * branches and a bark strip, in colour and in a separate cut-out alpha), and one impostor
 * atlas per group (16 views of each species at 256 px, with view-space normals for the
 * deciduous). Twenty-eight GLB models carry the trees themselves: four variants per
 * species, one per stem and card seed, each UV-mapped into its species' column.
 *
 * THE LAYOUT IS READ, NOT WRITTEN DOWN. Cell rectangles, column and row counts, the
 * species each column holds, the cell's world size and where the bark strip begins are
 * all in `public/look/manifest.json`, generated by the asset pipeline that produced the
 * files — and the pipeline is still growing them (a species is re-rendered in place, and
 * a re-render moves rectangles). A hard-coded rectangle is a broken tree the day an atlas
 * is rebuilt, so the manifest is fetched once and every number here comes from it. The
 * FILE NAMES are a table, the way `groundtextures.ts` names the ground's photographs:
 * they are the pipeline's naming convention, and a season is a table row.
 *
 * ONLY THE SEASONS IN PLAY ARE RESIDENT. The season is continuous and the atlas is a set
 * of four, so the material blends the two heaviest (`LookPalette.groundForestA/B`). Two
 * sets of 4K atlases is 150 MB of texture; four would be twice a phone's budget, so
 * `retainTreeTextures` is handed the pair and disposes whatever else has been loaded.
 * A pair changes a few times a game year, and the season's own weight rises over days, so
 * the newly-named set is in place long before it is more than a few percent of the mix.
 *
 * NOTHING HERE FAILS A WORLD. Fetching the manifest needs `fetch` and a GLB needs a
 * loader, and the headless tools have neither; both paths return null and the tree layer
 * simply does not exist, the contract the ground's photographs and the bushes' cards are
 * already on.
 */

/** The six species with an asset of their own, in the impostor atlases' own order. */
export type TreeSpecies = 'birch' | 'aspen' | 'oak' | 'lime' | 'spruce' | 'pine';

/** The two model atlases, whose layouts differ. */
export type TreeAtlasGroup = 'deciduous' | 'conifer';

/** Everything about the atlases' geometry that the renderer needs, from the manifest. */
export interface TreeLayout {
  /** Columns in the model atlas: u = (column + u) / columns. */
  readonly columns: Record<TreeAtlasGroup, number>;
  /** The column each species owns in its model atlas. */
  readonly column: Record<TreeSpecies, number>;
  /** The impostor atlas' row count and the row each species owns (row = v band). */
  readonly rows: Record<TreeAtlasGroup, number>;
  readonly row: Record<TreeSpecies, number>;
  /** Views round the tree in the impostor atlas. */
  readonly views: number;
  /** One impostor cell's world size, metres: the quad a tree is drawn as. */
  readonly cellM: number;
  /** One impostor cell's size in texels. */
  readonly cellPx: number;
  /**
   * The top-down v at which a model column stops being cards and becomes the bark strip.
   * Read from the manifest's px rectangle, so a re-render that moves the strip moves this
   * with it.
   */
  readonly barkFromV: Record<TreeAtlasGroup, number>;
  /** Which species lives in which atlas. */
  readonly group: Record<TreeSpecies, TreeAtlasGroup>;
  /** How many GLB variants each species and each of the two low models has. */
  readonly variants: Record<TreeSpecies, number>;
  readonly stumpVariants: number;
  readonly logVariants: number;
}

/** The five photographs a season's trees are drawn from, by file under `/look/`. */
export interface TreeSeasonFiles {
  readonly deciduous: string;
  readonly conifer: string;
  readonly coniferAlpha: string;
  readonly imposterDeciduous: string;
  readonly imposterConifer: string;
}

/** `SEASON_ORDER` of `world/look/palette.ts`: spring, summer, autumn, winter. */
export const TREE_SEASON_FILES: readonly TreeSeasonFiles[] = [
  {
    deciduous: 'trees_deciduous_spring.webp',
    conifer: 'trees_conifer_spring_m.webp',
    coniferAlpha: 'trees_conifer_spring_a.webp',
    imposterDeciduous: 'imposters_deciduous_spring_d.webp',
    imposterConifer: 'imposters_conifer_spring_d.webp',
  },
  {
    deciduous: 'trees_deciduous_summer.webp',
    conifer: 'trees_conifer_summer_m.webp',
    coniferAlpha: 'trees_conifer_summer_a.webp',
    imposterDeciduous: 'imposters_deciduous_summer_d.webp',
    imposterConifer: 'imposters_conifer_summer_d.webp',
  },
  {
    deciduous: 'trees_deciduous_autumn.webp',
    conifer: 'trees_conifer_autumn_m.webp',
    coniferAlpha: 'trees_conifer_autumn_a.webp',
    imposterDeciduous: 'imposters_deciduous_autumn_d.webp',
    imposterConifer: 'imposters_conifer_autumn_d.webp',
  },
  {
    deciduous: 'trees_deciduous_winter.webp',
    conifer: 'trees_conifer_winter_m.webp',
    coniferAlpha: 'trees_conifer_winter_a.webp',
    imposterDeciduous: 'imposters_deciduous_winter_d.webp',
    imposterConifer: 'imposters_conifer_winter_d.webp',
  },
];

/**
 * The normals and the conifer alpha are one file for the whole year: the crown geometry
 * the pipeline bakes them from is the same in every season (only the leaves' paint
 * changes), so the manifest names them without a season. They are never disposed.
 */
export const TREE_SHARED_FILES = {
  deciduousNormal: 'trees_deciduous_summer_n.webp',
  imposterDeciduousNormal: 'imposters_deciduous_summer_n.webp',
  imposterConiferNormal: 'imposters_conifer_n.webp',
} as const;

const SPECIES_NAMES = ['birch', 'aspen', 'oak', 'lime', 'spruce', 'pine'] as const;

interface ManifestFile {
  readonly group?: string;
  readonly file?: string;
  readonly size?: readonly [number, number] | null;
  readonly role?: string;
  readonly layout?: Record<string, unknown>;
}

let manifestPromise: Promise<TreeLayout | null> | null = null;

/**
 * The atlas layout, from `public/look/manifest.json`. The *summer* entries carry it: the
 * season is a paint, the layout is the sheet, and a season that is being re-rendered in
 * place must not take the layout with it.
 */
export function treeLayout(): Promise<TreeLayout | null> {
  manifestPromise ??= (async () => {
    try {
      const response = await fetch('/look/manifest.json');
      if (!response.ok) return null;
      const body = (await response.json()) as { files?: Record<string, ManifestFile> };
      return readLayout(body.files ?? {});
    } catch {
      return null;
    }
  })();
  return manifestPromise;
}

function layoutOf(files: Record<string, ManifestFile>, file: string): Record<string, unknown> {
  return files[file]?.layout ?? {};
}

function readLayout(files: Record<string, ManifestFile>): TreeLayout | null {
  const deciduous = layoutOf(files, 'trees_deciduous_summer.webp');
  const conifer = layoutOf(files, 'trees_conifer_summer_m.webp');
  const imposterDeciduous = layoutOf(files, 'imposters_deciduous_summer_d.webp');
  const imposterConifer = layoutOf(files, 'imposters_conifer_summer_d.webp');
  const speciesList = (source: Record<string, unknown>): string[] =>
    Array.isArray(source['column_species']) ? (source['column_species'] as string[]) : [];
  const rowList = (source: Record<string, unknown>): string[] =>
    Array.isArray(source['row_species']) ? (source['row_species'] as string[]) : [];
  // WHERE THE BARK STRIP BEGINS, in the top-down v every tree texture is read in: the
  // strip's own px rectangle over the sheet's height (the manifest measures px from the
  // top, as the sampler now does). Above this v a column's texels are bark, below it they
  // are cards — one test, and the same number for both atlases today.
  const barkFrom = (source: Record<string, unknown>, file: string): number => {
    const strip = source['bark_strip'] as { px?: { y?: number; h?: number } } | undefined;
    const height = files[file]?.size?.[1];
    const y = strip?.px?.y;
    if (typeof y === 'number' && typeof height === 'number' && height > 0) return y / height;
    return 0.75;
  };
  const deciduousSpecies = speciesList(deciduous);
  const coniferSpecies = speciesList(conifer);
  const deciduousRows = rowList(imposterDeciduous);
  const coniferRows = rowList(imposterConifer);
  if (deciduousSpecies.length === 0 || coniferSpecies.length === 0) return null;

  const column: Record<string, number> = {};
  for (const [index, name] of deciduousSpecies.entries()) column[name] = index;
  for (const [index, name] of coniferSpecies.entries()) column[name] = index;
  const row: Record<string, number> = {};
  for (const [index, name] of deciduousRows.entries()) row[name] = index;
  for (const [index, name] of coniferRows.entries()) row[name] = index;
  const variants: Record<string, number> = {};
  let stumpVariants = 0;
  let logVariants = 0;
  for (const file of Object.keys(files)) {
    const model = /^tree_([a-z]+)_(\d+)\.glb$/.exec(file);
    if (model) {
      const name = model[1]!;
      variants[name] = Math.max(variants[name] ?? 0, Number(model[2]) + 1);
      continue;
    }
    const low = /^tree_(stump|log)_(\d+)\.glb$/.exec(file);
    if (low) {
      const count = Number(low[2]) + 1;
      if (low[1] === 'stump') stumpVariants = Math.max(stumpVariants, count);
      else logVariants = Math.max(logVariants, count);
    }
  }
  const group: Record<string, TreeAtlasGroup> = {};
  for (const name of speciesList(deciduous)) group[name] = 'deciduous';
  for (const name of speciesList(conifer)) group[name] = 'conifer';
  for (const name of SPECIES_NAMES) {
    if (column[name] === undefined || row[name] === undefined || !variants[name]) return null;
  }
  const cellsX = Number(imposterDeciduous['cells_x']) || 16;
  const cellM = Number(imposterDeciduous['cell_world_m']) || 12.4;
  const cellPx = Number(imposterDeciduous['cell_px']) || 256;
  return {
    columns: {
      deciduous: Number(deciduous['columns']) || deciduousSpecies.length,
      conifer: Number(conifer['columns']) || coniferSpecies.length,
    },
    column: column as Record<TreeSpecies, number>,
    rows: {
      deciduous: Number(imposterDeciduous['rows']) || deciduousRows.length,
      conifer: Number(imposterConifer['rows']) || coniferRows.length,
    },
    row: row as Record<TreeSpecies, number>,
    views: Math.max(2, cellsX),
    cellM,
    cellPx,
    barkFromV: {
      deciduous: barkFrom(deciduous, 'trees_deciduous_summer.webp'),
      conifer: barkFrom(conifer, 'trees_conifer_summer_m.webp'),
    },
    group: group as Record<TreeSpecies, TreeAtlasGroup>,
    variants: variants as Record<TreeSpecies, number>,
    stumpVariants: Math.max(1, stumpVariants),
    logVariants: Math.max(1, logVariants),
  };
}

// ---------------------------------------------------------------------------
// The photographs

const textures = new Map<string, THREE.Texture>();

/**
 * One tree texture, by file under `/look/`, loaded once and kept until
 * `retainTreeTextures` says the season it belongs to is out of play. Colour space is part
 * of the data: an albedo is sRGB so the sampler returns linear light, a cut-out mask and
 * a normal map are numbers and stay linear.
 */
export function treeTexture(file: string, srgb: boolean): THREE.Texture {
  const have = textures.get(file);
  if (have) return have;
  const loader = imageLoader();
  const texture = loader ? loader.load(`/look/${file}`) : new THREE.Texture();
  // THE TREE ATLASES ARE READ TOP-DOWN. A model's uv comes out of a glTF file, and glTF
  // measures v from the TOP of the image — which is why GLTFLoader loads a texture with
  // `flipY = false`; with three's default the whole sheet is mirrored, and a mirror of the
  // clump rows [0, 0.75] is the bark strip. The impostor cells are computed from the
  // manifest's own px rectangles, which are top-down too, so every tree texture uses this
  // one convention and no consumer has to remember which way round it is.
  texture.flipY = false;
  texture.wrapS = THREE.RepeatWrapping;
  // A model's bark strip wraps along the trunk (u runs past 1); nothing samples past v.
  texture.wrapT = THREE.ClampToEdgeWrapping;
  texture.minFilter = THREE.LinearMipmapLinearFilter;
  texture.magFilter = THREE.LinearFilter;
  texture.anisotropy = maxAnisotropy();
  texture.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
  texture.name = file;
  textures.set(file, texture);
  return texture;
}

/** Drops every tree texture but the named ones: the seasons in play are the ones loaded. */
export function retainTreeTextures(files: readonly string[]): void {
  const keep = new Set(files);
  for (const name of Object.values(TREE_SHARED_FILES)) keep.add(name);
  for (const [file, texture] of textures) {
    if (keep.has(file)) continue;
    texture.dispose();
    textures.delete(file);
  }
}

/** Every file the two named seasons need, for `retainTreeTextures`. */
export function treeSeasonFiles(a: number, b: number): string[] {
  const out: string[] = [];
  for (const index of [a, b]) {
    const season = TREE_SEASON_FILES[index % TREE_SEASON_FILES.length]!;
    out.push(season.deciduous, season.conifer, season.coniferAlpha, season.imposterDeciduous, season.imposterConifer);
  }
  return out;
}

// ---------------------------------------------------------------------------
// The models

/** One model, as the renderer draws it: vertices, normals, atlas uv and the baked colours. */
export interface TreeModels {
  /** `[species][variant]`, in `SPECIES_NAMES` order. */
  readonly tree: readonly (readonly THREE.BufferGeometry[])[];
  readonly stump: readonly THREE.BufferGeometry[];
  readonly log: readonly THREE.BufferGeometry[];
}

export const SPECIES_ORDER: readonly TreeSpecies[] = SPECIES_NAMES;

/**
 * A model's vertex colours are the pipeline's per-leaf bake (how turned the leaf is, how
 * bright, how shaded — see the asset log) and are read by name, so the geometry is
 * normalised once on the way in: `aTreeCol` as three floats, no second uv set, and a
 * bounding sphere for culling. The GLB has no material: every colour a tree has comes from
 * an atlas, and every light from the game.
 */
function prepareModel(geometry: THREE.BufferGeometry): THREE.BufferGeometry {
  const colours = geometry.getAttribute('color');
  if (colours) {
    const out = new Float32Array(geometry.getAttribute('position').count * 3);
    for (let i = 0; i < out.length; i += 3) {
      out[i] = colours.getX(i / 3);
      out[i + 1] = colours.getY(i / 3);
      out[i + 2] = colours.getZ(i / 3);
    }
    geometry.setAttribute('aTreeCol', new THREE.BufferAttribute(out, 3));
    geometry.deleteAttribute('color');
  } else {
    geometry.setAttribute('aTreeCol', new THREE.BufferAttribute(new Float32Array(geometry.getAttribute('position').count * 3).fill(1), 3));
  }
  geometry.deleteAttribute('uv1');
  geometry.deleteAttribute('uv2');
  geometry.computeBoundingSphere();
  return geometry;
}

let modelsPromise: Promise<TreeModels | null> | null = null;

/**
 * Every tree model, loaded once. Twenty-eight small files (16-25 kB each, about 170
 * vertices apiece) and four low ones, so the whole set is one round of requests and no
 * streaming: a variant that is missing when its first tree is drawn is a hole in a wood.
 */
export function treeModels(layout: TreeLayout): Promise<TreeModels | null> {
  modelsPromise ??= (async () => {
    try {
      const loader = new GLTFLoader();
      const load = async (file: string): Promise<THREE.BufferGeometry> => {
        const scene = (await loader.loadAsync(`/look/${file}`)).scene;
        let source: THREE.BufferGeometry | null = null;
        scene.traverse((object) => {
          const mesh = object as THREE.Mesh;
          if (!source && mesh.isMesh) source = mesh.geometry;
        });
        if (!source) throw new Error(`${file} carries no mesh`);
        return prepareModel((source as THREE.BufferGeometry).clone());
      };
      const tree = await Promise.all(
        SPECIES_NAMES.map((name) =>
          Promise.all(
            Array.from({ length: layout.variants[name]! }, (_unused, variant) => load(`tree_${name}_${variant}.glb`)),
          ),
        ),
      );
      const stump = await Promise.all(
        Array.from({ length: layout.stumpVariants }, (_unused, variant) => load(`tree_stump_${variant}.glb`)),
      );
      const log = await Promise.all(
        Array.from({ length: layout.logVariants }, (_unused, variant) => load(`tree_log_${variant}.glb`)),
      );
      return { tree, stump, log };
    } catch {
      return null;
    }
  })();
  return modelsPromise;
}
